import type { ServiceAddon, ServicePackage } from "@/lbs/types";

/** Suggested catalog prices — editable per proposal in the builder. */
export type CatalogPackageSeed = Omit<
  ServicePackage,
  "id" | "org_id" | "created_at" | "updated_at"
>;

export type CatalogAddonSeed = Omit<
  ServiceAddon,
  "id" | "org_id" | "created_at" | "updated_at"
>;

export const LBS_SERVICE_PACKAGES: CatalogPackageSeed[] = [
  {
    name: "Website Starter",
    description:
      "Up to 4-page custom-coded responsive site with basic SEO and a contact form. Ideal for contractors getting started online.",
    category: "web",
    billing_type: "one_time",
    billing_interval: null,
    suggested_price: 1200,
    currency: "USD",
    active: true,
    sort_order: 1,
  },
  {
    name: "Website Pro",
    description:
      "Multi-page custom site with client dashboard, lead capture, advanced SEO structure, and component architecture. LBS flagship offering.",
    category: "web",
    billing_type: "one_time",
    billing_interval: null,
    suggested_price: 2800,
    currency: "USD",
    active: true,
    sort_order: 2,
  },
  {
    name: "Website Premium",
    description:
      "Everything in Pro plus 3D/animation design, integrations (CRM, calendar, payments), and professional bilingual copy.",
    category: "web",
    billing_type: "one_time",
    billing_interval: null,
    suggested_price: 4500,
    currency: "USD",
    active: true,
    sort_order: 3,
  },
  {
    name: "Website Redesign",
    description:
      "Full redesign of an existing site: new look, SEO and speed improvements, conversion focus, same domain.",
    category: "web",
    billing_type: "one_time",
    billing_interval: null,
    suggested_price: 1900,
    currency: "USD",
    active: true,
    sort_order: 4,
  },
  {
    name: "Marketing Starter",
    description:
      "Google Ads or Meta Ads management for one objective with monthly results reporting. Ad spend not included.",
    category: "marketing",
    billing_type: "recurring",
    billing_interval: "monthly",
    suggested_price: 600,
    currency: "USD",
    active: true,
    sort_order: 10,
  },
  {
    name: "Marketing Growth",
    description:
      "Multi-channel ads plus ongoing SEO, monthly reporting and optimization for scaling leads.",
    category: "marketing",
    billing_type: "recurring",
    billing_interval: "monthly",
    suggested_price: 1200,
    currency: "USD",
    active: true,
    sort_order: 11,
  },
  {
    name: "SKOP — Scope to ESX",
    description:
      "SKOP platform access for scope-to-ESX (Xactimate) conversion for contractors and adjusters. Support included.",
    category: "skop",
    billing_type: "recurring",
    billing_interval: "monthly",
    suggested_price: 149,
    currency: "USD",
    active: true,
    sort_order: 20,
  },
  {
    name: "SKOP — Team / Pro",
    description:
      "SKOP for teams: multiple users, higher conversion volume, priority support.",
    category: "skop",
    billing_type: "recurring",
    billing_interval: "monthly",
    suggested_price: 399,
    currency: "USD",
    active: true,
    sort_order: 21,
  },
];

export const LBS_SERVICE_ADDONS: CatalogAddonSeed[] = [
  {
    name: "Logo design",
    description:
      "Professional logo design with 3 concepts and deliverables in all standard formats.",
    category: "design",
    billing_type: "one_time",
    billing_interval: null,
    suggested_price: 350,
    currency: "USD",
    package_id: null,
    active: true,
    sort_order: 1,
  },
  {
    name: "Brand identity",
    description:
      "Logo plus color palette, typography, and a basic brand guidelines document.",
    category: "design",
    billing_type: "one_time",
    billing_interval: null,
    suggested_price: 700,
    currency: "USD",
    package_id: null,
    active: true,
    sort_order: 2,
  },
  {
    name: "Business card / stationery design",
    description: "Business card and basic stationery templates.",
    category: "design",
    billing_type: "one_time",
    billing_interval: null,
    suggested_price: 180,
    currency: "USD",
    package_id: null,
    active: true,
    sort_order: 3,
  },
  {
    name: "Additional page",
    description: "Extra page beyond those included in the selected package.",
    category: "web",
    billing_type: "one_time",
    billing_interval: null,
    suggested_price: 150,
    currency: "USD",
    package_id: null,
    active: true,
    sort_order: 10,
  },
  {
    name: "Blog / news section",
    description: "Blog module with post management.",
    category: "web",
    billing_type: "one_time",
    billing_interval: null,
    suggested_price: 400,
    currency: "USD",
    package_id: null,
    active: true,
    sort_order: 11,
  },
  {
    name: "Bilingual site (ES/EN)",
    description: "Two-language site with language switcher.",
    category: "web",
    billing_type: "one_time",
    billing_interval: null,
    suggested_price: 500,
    currency: "USD",
    package_id: null,
    active: true,
    sort_order: 12,
  },
  {
    name: "Payment integration",
    description: "Connect a payment gateway (e.g. Stripe) to the site.",
    category: "web",
    billing_type: "one_time",
    billing_interval: null,
    suggested_price: 450,
    currency: "USD",
    package_id: null,
    active: true,
    sort_order: 13,
  },
  {
    name: "Booking / scheduling",
    description: "Integrated appointment or booking system.",
    category: "web",
    billing_type: "one_time",
    billing_interval: null,
    suggested_price: 400,
    currency: "USD",
    package_id: null,
    active: true,
    sort_order: 14,
  },
  {
    name: "Extra client dashboard",
    description: "Additional customized client dashboard panel.",
    category: "web",
    billing_type: "one_time",
    billing_interval: null,
    suggested_price: 600,
    currency: "USD",
    package_id: null,
    active: true,
    sort_order: 15,
  },
  {
    name: "On-page SEO (setup)",
    description:
      "Initial SEO optimization: metadata, structure, and performance basics.",
    category: "seo",
    billing_type: "one_time",
    billing_interval: null,
    suggested_price: 500,
    currency: "USD",
    package_id: null,
    active: true,
    sort_order: 20,
  },
  {
    name: "Professional copywriting",
    description: "Professional copy for up to 5 site pages.",
    category: "seo",
    billing_type: "one_time",
    billing_interval: null,
    suggested_price: 300,
    currency: "USD",
    package_id: null,
    active: true,
    sort_order: 21,
  },
  {
    name: "Google Business Profile",
    description: "Google Business Profile setup and optimization.",
    category: "seo",
    billing_type: "one_time",
    billing_interval: null,
    suggested_price: 200,
    currency: "USD",
    package_id: null,
    active: true,
    sort_order: 22,
  },
  {
    name: "Photography / stock images",
    description: "Curated and edited professional images for the site.",
    category: "seo",
    billing_type: "one_time",
    billing_interval: null,
    suggested_price: 250,
    currency: "USD",
    package_id: null,
    active: true,
    sort_order: 23,
  },
  {
    name: "Managed hosting",
    description:
      "Hosting, domain, SSL, and monitoring managed by LBS.",
    category: "hosting",
    billing_type: "recurring",
    billing_interval: "monthly",
    suggested_price: 25,
    currency: "USD",
    package_id: null,
    active: true,
    sort_order: 30,
  },
  {
    name: "Website maintenance",
    description:
      "Updates, backups, support, and minor monthly content changes.",
    category: "hosting",
    billing_type: "recurring",
    billing_interval: "monthly",
    suggested_price: 80,
    currency: "USD",
    package_id: null,
    active: true,
    sort_order: 31,
  },
  {
    name: "Maintenance + priority support",
    description:
      "Maintenance with priority response and included change hours.",
    category: "hosting",
    billing_type: "recurring",
    billing_interval: "monthly",
    suggested_price: 150,
    currency: "USD",
    package_id: null,
    active: true,
    sort_order: 32,
  },
  {
    name: "Monthly web audit report",
    description:
      "Automated performance/SEO report (Nomi Web Report) delivered monthly.",
    category: "hosting",
    billing_type: "recurring",
    billing_interval: "monthly",
    suggested_price: 40,
    currency: "USD",
    package_id: null,
    active: true,
    sort_order: 33,
  },
  {
    name: "SKOP — Additional user",
    description: "Extra user seat on a SKOP account.",
    category: "skop",
    billing_type: "recurring",
    billing_interval: "monthly",
    suggested_price: 49,
    currency: "USD",
    package_id: null,
    active: true,
    sort_order: 40,
  },
  {
    name: "SKOP — Onboarding / training",
    description: "Initial training session to get started with SKOP.",
    category: "skop",
    billing_type: "one_time",
    billing_interval: null,
    suggested_price: 200,
    currency: "USD",
    package_id: null,
    active: true,
    sort_order: 41,
  },
];
