export {
  splitHtmlEmail,
  splitPlainTextEmail,
  stripComposerQuotedHtml,
  stripComposerQuotedPlainText,
  stripQuotedHtml,
  stripQuotedPlainText,
  prepareQuotedHtmlForDisplay,
  prepareQuotedPlainForDisplay,
  hasSubstantialQuotedContent,
  hasRichHtmlStructure,
  hasHtmlForwardMarker,
  hasPlainForwardMarker,
  isForwardedStyleEmail,
  isForwardedStylePlainEmail,
  isPlainTextSimilar,
  visibleEmailTextLength,
  type SplitEmailContent,
} from "../../../supabase/functions/_shared/ticketEmailQuotedContent.ts";
