create table if not exists public.people (
  id bigint generated by default as identity primary key,
  org_id bigint not null default 1,
  type text not null check (type in ('employee', 'salesperson', 'subcontractor')),
  first_name text not null,
  last_name text not null,
  phone text,
  email text,
  status text not null default 'active' check (status in ('active', 'inactive')),
  pay_type text not null check (pay_type in ('hourly', 'salary', 'commission', 'day_rate')),
  hourly_rate numeric(12,2),
  salary_rate numeric(12,2),
  day_rate numeric(12,2),
  commission_rate numeric(8,4),
  created_at timestamp with time zone not null default now()
);

create table if not exists public.time_entries (
  id bigint generated by default as identity primary key,
  org_id bigint not null default 1,
  person_id bigint not null references public.people(id) on update cascade on delete restrict,
  project_id bigint not null references public.deals(id) on update cascade on delete restrict,
  date date not null,
  hours numeric(8,2) not null check (hours >= 0),
  start_time time,
  end_time time,
  notes text,
  status text not null default 'draft' check (status in ('draft', 'approved', 'paid')),
  created_at timestamp with time zone not null default now()
);

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  org_id bigint not null default 1,
  pay_period_start date not null,
  pay_period_end date not null,
  pay_date date not null,
  status text not null default 'draft' check (status in ('draft', 'approved', 'paid')),
  total_gross numeric(14,2),
  total_net numeric(14,2),
  created_at timestamp with time zone not null default now(),
  check (pay_period_start <= pay_period_end)
);

create table if not exists public.payment_lines (
  id bigint generated by default as identity primary key,
  payment_id bigint not null references public.payments(id) on update cascade on delete cascade,
  person_id bigint not null references public.people(id) on update cascade on delete restrict,
  project_id bigint references public.deals(id) on update cascade on delete set null,
  source_type text not null check (source_type in ('time_entry', 'salary', 'commission', 'adjustment')),
  source_id bigint,
  qty_hours numeric(8,2),
  rate numeric(12,2),
  amount numeric(14,2) not null,
  notes text,
  created_at timestamp with time zone not null default now()
);

create unique index if not exists payment_lines_source_unique
  on public.payment_lines (source_type, source_id)
  where source_id is not null and source_type in ('time_entry', 'commission');

create index if not exists people_org_id_idx on public.people (org_id);
create index if not exists people_type_idx on public.people (type);
create index if not exists people_status_idx on public.people (status);

create index if not exists time_entries_org_id_idx on public.time_entries (org_id);
create index if not exists time_entries_person_id_idx on public.time_entries (person_id);
create index if not exists time_entries_project_id_idx on public.time_entries (project_id);
create index if not exists time_entries_date_idx on public.time_entries (date);
create index if not exists time_entries_status_idx on public.time_entries (status);

create index if not exists payments_org_id_idx on public.payments (org_id);
create index if not exists payments_period_idx on public.payments (pay_period_start, pay_period_end);
create index if not exists payments_status_idx on public.payments (status);
create index if not exists payments_pay_date_idx on public.payments (pay_date);

create index if not exists payment_lines_payment_id_idx on public.payment_lines (payment_id);
create index if not exists payment_lines_person_id_idx on public.payment_lines (person_id);
create index if not exists payment_lines_project_id_idx on public.payment_lines (project_id);
create index if not exists payment_lines_source_idx on public.payment_lines (source_type, source_id);

alter table public.people enable row level security;
alter table public.time_entries enable row level security;
alter table public.payments enable row level security;
alter table public.payment_lines enable row level security;

grant delete, insert, select, update on table public.people to authenticated;
grant delete, insert, select, update on table public.time_entries to authenticated;
grant delete, insert, select, update on table public.payments to authenticated;
grant delete, insert, select, update on table public.payment_lines to authenticated;

grant delete, insert, references, select, trigger, truncate, update on table public.people to service_role;
grant delete, insert, references, select, trigger, truncate, update on table public.time_entries to service_role;
grant delete, insert, references, select, trigger, truncate, update on table public.payments to service_role;
grant delete, insert, references, select, trigger, truncate, update on table public.payment_lines to service_role;

create policy "People insert" on public.people as permissive for insert to authenticated with check (true);
create policy "People select" on public.people as permissive for select to authenticated using (true);
create policy "People update" on public.people as permissive for update to authenticated using (true) with check (true);
create policy "People delete" on public.people as permissive for delete to authenticated using (true);

create policy "Time entries insert" on public.time_entries as permissive for insert to authenticated with check (true);
create policy "Time entries select" on public.time_entries as permissive for select to authenticated using (true);
create policy "Time entries update" on public.time_entries as permissive for update to authenticated using (true) with check (true);
create policy "Time entries delete" on public.time_entries as permissive for delete to authenticated using (true);

create policy "Payments insert" on public.payments as permissive for insert to authenticated with check (true);
create policy "Payments select" on public.payments as permissive for select to authenticated using (true);
create policy "Payments update" on public.payments as permissive for update to authenticated using (true) with check (true);
create policy "Payments delete" on public.payments as permissive for delete to authenticated using (true);

create policy "Payment lines insert" on public.payment_lines as permissive for insert to authenticated with check (true);
create policy "Payment lines select" on public.payment_lines as permissive for select to authenticated using (true);
create policy "Payment lines update" on public.payment_lines as permissive for update to authenticated using (true) with check (true);
create policy "Payment lines delete" on public.payment_lines as permissive for delete to authenticated using (true);

create or replace function public.generate_payment_lines(p_payment_id bigint)
returns integer
language plpgsql
security invoker
as $$
declare
  v_payment public.payments%rowtype;
  v_inserted integer := 0;
  v_rowcount integer := 0;
begin
  select * into v_payment from public.payments where id = p_payment_id;
  if v_payment is null then
    raise exception 'Payment % not found', p_payment_id;
  end if;

  insert into public.payment_lines (
    payment_id,
    person_id,
    project_id,
    source_type,
    source_id,
    qty_hours,
    rate,
    amount,
    notes
  )
  select
    v_payment.id,
    te.person_id,
    te.project_id,
    'time_entry',
    te.id,
    te.hours,
    case
      when p.pay_type = 'hourly' then coalesce(p.hourly_rate, 0)
      when p.pay_type = 'day_rate' then coalesce(p.day_rate, 0) / 8
      else 0
    end as rate,
    round(
      te.hours * case
        when p.pay_type = 'hourly' then coalesce(p.hourly_rate, 0)
        when p.pay_type = 'day_rate' then coalesce(p.day_rate, 0) / 8
        else 0
      end,
      2
    ) as amount,
    concat('Generated from time entry #', te.id)
  from public.time_entries te
  inner join public.people p on p.id = te.person_id
  where te.org_id = v_payment.org_id
    and p.org_id = v_payment.org_id
    and te.status = 'approved'
    and te.date between v_payment.pay_period_start and v_payment.pay_period_end
    and not exists (
      select 1
      from public.payment_lines pl
      where pl.source_type = 'time_entry'
        and pl.source_id = te.id
    );

  get diagnostics v_rowcount = row_count;
  v_inserted := v_inserted + v_rowcount;

  insert into public.payment_lines (
    payment_id,
    person_id,
    project_id,
    source_type,
    source_id,
    qty_hours,
    rate,
    amount,
    notes
  )
  select
    v_payment.id,
    p.id,
    d.id,
    'commission',
    d.id,
    null,
    p.commission_rate,
    round((coalesce(d.amount, 0)::numeric * coalesce(p.commission_rate, 0)) / 100, 2),
    concat('Generated commission from project #', d.id)
  from public.deals d
  inner join public.people p on p.id = d.sales_id
  where p.type = 'salesperson'
    and p.org_id = v_payment.org_id
    and d.stage = 'won'
    and coalesce(d.expected_closing_date::date, d.created_at::date) between v_payment.pay_period_start and v_payment.pay_period_end
    and not exists (
      select 1
      from public.payment_lines pl
      where pl.source_type = 'commission'
        and pl.source_id = d.id
        and pl.person_id = p.id
    );

  get diagnostics v_rowcount = row_count;
  v_inserted := v_inserted + v_rowcount;

  update public.payments py
  set total_gross = lines.total_gross,
      total_net = lines.total_gross
  from (
    select payment_id, round(coalesce(sum(amount), 0), 2) as total_gross
    from public.payment_lines
    where payment_id = v_payment.id
    group by payment_id
  ) lines
  where py.id = lines.payment_id;

  return v_inserted;
end;
$$;

create or replace function public.mark_payment_time_entries_paid()
returns trigger
language plpgsql
as $$
begin
  if new.status = 'paid' and old.status is distinct from 'paid' then
    update public.time_entries te
    set status = 'paid'
    from public.payment_lines pl
    where pl.payment_id = new.id
      and pl.source_type = 'time_entry'
      and pl.source_id = te.id
      and te.status = 'approved';
  end if;
  return new;
end;
$$;

drop trigger if exists payments_mark_time_entries_paid on public.payments;
create trigger payments_mark_time_entries_paid
after update of status on public.payments
for each row
execute function public.mark_payment_time_entries_paid();

create or replace view public.report_project_profitability
with (security_invoker=on)
as
select
  d.id as id,
  d.id as project_id,
  d.name as project_name,
  coalesce(sum(te.hours), 0) as total_hours,
  round(
    coalesce(sum(
      case
        when p.pay_type = 'hourly' then te.hours * coalesce(p.hourly_rate, 0)
        when p.pay_type = 'day_rate' then te.hours * (coalesce(p.day_rate, 0) / 8)
        else 0
      end
    ), 0),
    2
  ) as total_labor_cost,
  coalesce(d.amount, 0)::numeric as total_revenue,
  round(
    coalesce(d.amount, 0)::numeric - coalesce(sum(
      case
        when p.pay_type = 'hourly' then te.hours * coalesce(p.hourly_rate, 0)
        when p.pay_type = 'day_rate' then te.hours * (coalesce(p.day_rate, 0) / 8)
        else 0
      end
    ), 0),
    2
  ) as profit,
  coalesce(max(te.date), d.created_at::date) as metric_date
from public.deals d
left join public.time_entries te on te.project_id = d.id and te.status in ('approved', 'paid')
left join public.people p on p.id = te.person_id
group by d.id, d.name, d.amount, d.created_at;

create or replace view public.report_payroll_summary
with (security_invoker=on)
as
select
  py.id,
  py.id as payment_id,
  py.org_id,
  py.pay_period_start,
  py.pay_period_end,
  py.pay_date,
  py.status,
  round(coalesce(sum(pl.amount), 0), 2) as total_gross,
  round(coalesce(sum(pl.amount), 0), 2) as total_net,
  count(pl.id) as lines_count
from public.payments py
left join public.payment_lines pl on pl.payment_id = py.id
group by py.id, py.org_id, py.pay_period_start, py.pay_period_end, py.pay_date, py.status;

create or replace view public.report_labor_cost_by_person
with (security_invoker=on)
as
select
  concat(te.person_id::text, '-', to_char(date_trunc('month', te.date), 'YYYY-MM')) as id,
  te.person_id,
  p.org_id,
  concat(p.first_name, ' ', p.last_name) as person_name,
  date_trunc('month', te.date)::date as period_month,
  count(te.id) as entries_count,
  coalesce(sum(te.hours), 0) as total_hours,
  round(
    coalesce(sum(
      case
        when p.pay_type = 'hourly' then te.hours * coalesce(p.hourly_rate, 0)
        when p.pay_type = 'day_rate' then te.hours * (coalesce(p.day_rate, 0) / 8)
        when p.pay_type = 'salary' then 0
        when p.pay_type = 'commission' then 0
        else 0
      end
    ), 0),
    2
  ) as total_labor_cost
from public.time_entries te
inner join public.people p on p.id = te.person_id
where te.status in ('approved', 'paid')
group by
  te.person_id,
  p.org_id,
  p.first_name,
  p.last_name,
  date_trunc('month', te.date);
  
create or replace view public.report_sales_commissions_by_salesperson
with (security_invoker=on)
as
select
  concat(pl.person_id::text, '-', py.id::text) as id,
  pl.person_id,
  py.id as payment_id,
  py.org_id,
  py.pay_date,
  concat(p.first_name, ' ', p.last_name) as salesperson_name,
  count(pl.id) as commission_lines,
  round(coalesce(sum(pl.amount), 0), 2) as total_commission
from public.payment_lines pl
inner join public.payments py on py.id = pl.payment_id
inner join public.people p on p.id = pl.person_id
where pl.source_type = 'commission'
  and p.type = 'salesperson'
group by pl.person_id, py.id, py.org_id, py.pay_date, p.first_name, p.last_name;

grant select on public.report_project_profitability to authenticated;
grant select on public.report_payroll_summary to authenticated;
grant select on public.report_labor_cost_by_person to authenticated;
grant select on public.report_sales_commissions_by_salesperson to authenticated;

grant select on public.report_project_profitability to service_role;
grant select on public.report_payroll_summary to service_role;
grant select on public.report_labor_cost_by_person to service_role;
grant select on public.report_sales_commissions_by_salesperson to service_role;