-- Safe to re-run: skips objects that already exist.
-- Use this in Supabase SQL Editor if apply-pending-migrations.sql failed partway.

-- ===== 20260629140000_task_assignees.sql =====

alter table public.tasks
  add column if not exists assignee_person_ids bigint[] not null default '{}',
  add column if not exists collaborator_person_ids bigint[] not null default '{}';

create index if not exists tasks_assignee_person_ids_idx
  on public.tasks using gin (assignee_person_ids);

create index if not exists tasks_collaborator_person_ids_idx
  on public.tasks using gin (collaborator_person_ids);

create table if not exists public.task_assignees (
  id bigint generated by default as identity primary key,
  task_id bigint not null references public.tasks(id) on update cascade on delete cascade,
  person_id bigint not null references public.people(id) on update cascade on delete restrict,
  role text not null default 'collaborator'
    check (role in ('assignee', 'collaborator', 'watcher')),
  created_at timestamptz not null default now(),
  unique (task_id, person_id)
);

create index if not exists task_assignees_task_id_idx on public.task_assignees(task_id);
create index if not exists task_assignees_person_id_idx on public.task_assignees(person_id);

alter table public.task_assignees enable row level security;

grant delete, insert, select, update on table public.task_assignees to authenticated;
grant delete, insert, references, select, trigger, truncate, update on table public.task_assignees to service_role;

drop policy if exists "task_assignees_select" on public.task_assignees;
create policy "task_assignees_select" on public.task_assignees
  for select to authenticated
  using (
    exists (
      select 1
      from public.tasks t
      where t.id = task_assignees.task_id
        and t.org_id = public.current_user_org_id()
    )
  );

drop policy if exists "task_assignees_insert" on public.task_assignees;
create policy "task_assignees_insert" on public.task_assignees
  for insert to authenticated
  with check (
    exists (
      select 1
      from public.tasks t
      where t.id = task_assignees.task_id
        and t.org_id = public.current_user_org_id()
    )
  );

drop policy if exists "task_assignees_update" on public.task_assignees;
create policy "task_assignees_update" on public.task_assignees
  for update to authenticated
  using (
    exists (
      select 1
      from public.tasks t
      where t.id = task_assignees.task_id
        and t.org_id = public.current_user_org_id()
    )
  )
  with check (
    exists (
      select 1
      from public.tasks t
      where t.id = task_assignees.task_id
        and t.org_id = public.current_user_org_id()
    )
  );

drop policy if exists "task_assignees_delete" on public.task_assignees;
create policy "task_assignees_delete" on public.task_assignees
  for delete to authenticated
  using (
    exists (
      select 1
      from public.tasks t
      where t.id = task_assignees.task_id
        and t.org_id = public.current_user_org_id()
    )
  );

create table if not exists public.task_tag_notifications (
  id bigint generated by default as identity primary key,
  task_id bigint not null references public.tasks(id) on update cascade on delete cascade,
  person_id bigint not null references public.people(id) on update cascade on delete cascade,
  recipient_organization_member_id bigint not null
    references public.organization_members(id) on update cascade on delete cascade,
  read_at timestamptz,
  created_at timestamptz not null default now(),
  unique (task_id, person_id, recipient_organization_member_id)
);

create index if not exists task_tag_notifications_recipient_unread_idx
  on public.task_tag_notifications (recipient_organization_member_id)
  where read_at is null;

alter table public.task_tag_notifications enable row level security;

grant delete, insert, select, update on table public.task_tag_notifications to authenticated;
grant delete, insert, references, select, trigger, truncate, update on table public.task_tag_notifications to service_role;

drop policy if exists "task_tag_notifications_select" on public.task_tag_notifications;
create policy "task_tag_notifications_select" on public.task_tag_notifications
  for select to authenticated
  using (
    recipient_organization_member_id in (
      select om.id
      from public.organization_members om
      where om.user_id = auth.uid()
    )
  );

drop policy if exists "task_tag_notifications_update" on public.task_tag_notifications;
create policy "task_tag_notifications_update" on public.task_tag_notifications
  for update to authenticated
  using (
    recipient_organization_member_id in (
      select om.id
      from public.organization_members om
      where om.user_id = auth.uid()
    )
  )
  with check (
    recipient_organization_member_id in (
      select om.id
      from public.organization_members om
      where om.user_id = auth.uid()
    )
  );

create or replace function public.trg_task_assignee_notify()
returns trigger
language plpgsql
security definer
set search_path = public
as $fn$
declare
  v_person_email text;
  v_org_id bigint;
  v_member_id bigint;
begin
  select p.email, t.org_id
  into v_person_email, v_org_id
  from public.people p
  join public.tasks t on t.id = new.task_id
  where p.id = new.person_id;

  if v_person_email is null or btrim(v_person_email) = '' then
    return new;
  end if;

  select om.id
  into v_member_id
  from public.organization_members om
  where om.org_id = v_org_id
    and lower(btrim(om.email)) = lower(btrim(v_person_email))
    and coalesce(om.disabled, false) = false
  limit 1;

  if v_member_id is not null then
    insert into public.task_tag_notifications (
      task_id,
      person_id,
      recipient_organization_member_id
    )
    values (new.task_id, new.person_id, v_member_id)
    on conflict (task_id, person_id, recipient_organization_member_id) do nothing;
  end if;

  return new;
end;
$fn$;

drop trigger if exists trg_task_assignee_notify on public.task_assignees;

create trigger trg_task_assignee_notify
  after insert on public.task_assignees
  for each row
  execute function public.trg_task_assignee_notify();

-- ===== 20260629150000_task_mention_members_and_legacy_migration.sql =====

alter table public.tasks
  add column if not exists mentioned_member_ids bigint[] not null default '{}';

create index if not exists tasks_mentioned_member_ids_idx
  on public.tasks using gin (mentioned_member_ids);

alter table public.task_tag_notifications
  alter column person_id drop not null;

alter table public.task_tag_notifications
  drop constraint if exists task_tag_notifications_task_id_person_id_recipient_organization_member_id_key;

create unique index if not exists task_tag_notifications_person_tag_uidx
  on public.task_tag_notifications (task_id, person_id, recipient_organization_member_id)
  where person_id is not null;

create unique index if not exists task_tag_notifications_member_tag_uidx
  on public.task_tag_notifications (task_id, recipient_organization_member_id)
  where person_id is null;

create or replace function public.build_task_person_mention_token(person_id bigint)
returns text
language sql
stable
set search_path = public
as $$
  select '@[' || trim(both from coalesce(p.first_name, '') || ' ' || coalesce(p.last_name, '')) || '](person:' || p.id || ')'
  from public.people p
  where p.id = person_id;
$$;

create or replace function public.build_task_member_mention_token(member_id bigint)
returns text
language sql
stable
set search_path = public
as $$
  select '@[' || trim(both from coalesce(om.first_name, '') || ' ' || coalesce(om.last_name, '')) || '](member:' || om.id || ')'
  from public.organization_members om
  where om.id = member_id;
$$;

create or replace function public.migrate_legacy_task_mentions()
returns integer
language plpgsql
security definer
set search_path = public
as $fn$
declare
  updated_count integer := 0;
  task_row record;
  mention_tokens text := '';
  person_id bigint;
  member_ids bigint[] := '{}';
  original_text text;
  has_existing_mentions boolean;
begin
  for task_row in
    select
      t.id,
      t.text,
      t.organization_member_id,
      coalesce(t.assignee_person_ids, '{}'::bigint[]) as assignee_person_ids,
      coalesce(t.collaborator_person_ids, '{}'::bigint[]) as collaborator_person_ids
    from public.tasks t
  loop
    original_text := coalesce(task_row.text, '');
    has_existing_mentions := original_text ~ '@\[[^\]]+\]\((person|member):\d+\)';

    if has_existing_mentions then
      continue;
    end if;

    mention_tokens := '';

    foreach person_id in array task_row.assignee_person_ids loop
      mention_tokens := trim(both from concat_ws(
        ' ',
        mention_tokens,
        public.build_task_person_mention_token(person_id)
      ));
    end loop;

    foreach person_id in array task_row.collaborator_person_ids loop
      if person_id = any(task_row.assignee_person_ids) then
        continue;
      end if;
      mention_tokens := trim(both from concat_ws(
        ' ',
        mention_tokens,
        public.build_task_person_mention_token(person_id)
      ));
    end loop;

    if mention_tokens = '' and task_row.organization_member_id is not null then
      mention_tokens := public.build_task_member_mention_token(task_row.organization_member_id);
      member_ids := array[task_row.organization_member_id];
    end if;

    if mention_tokens = '' then
      continue;
    end if;

    update public.tasks
    set
      text = case
        when original_text = '' then mention_tokens
        else mention_tokens || ' — ' || original_text
      end,
      mentioned_member_ids = case
        when coalesce(array_length(member_ids, 1), 0) > 0 then member_ids
        else mentioned_member_ids
      end
    where id = task_row.id;

    updated_count := updated_count + 1;
  end loop;

  return updated_count;
end;
$fn$;

select public.migrate_legacy_task_mentions();

-- ===== 20260629160000_task_participants.sql =====

create table if not exists public.task_participants (
  id bigint generated by default as identity primary key,
  task_id bigint not null references public.tasks(id) on update cascade on delete cascade,
  person_id bigint references public.people(id) on update cascade on delete cascade,
  organization_member_id bigint references public.organization_members(id) on update cascade on delete cascade,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  constraint task_participants_person_or_member_chk check (
    (person_id is not null and organization_member_id is null)
    or (person_id is null and organization_member_id is not null)
  )
);

create unique index if not exists task_participants_task_person_uidx
  on public.task_participants (task_id, person_id)
  where person_id is not null;

create unique index if not exists task_participants_task_member_uidx
  on public.task_participants (task_id, organization_member_id)
  where organization_member_id is not null;

create index if not exists task_participants_task_id_idx
  on public.task_participants (task_id);

alter table public.task_participants enable row level security;

grant delete, insert, select, update on table public.task_participants to authenticated;
grant delete, insert, references, select, trigger, truncate, update on table public.task_participants to service_role;

drop policy if exists "task_participants_select" on public.task_participants;
create policy "task_participants_select" on public.task_participants
  for select to authenticated
  using (
    exists (
      select 1
      from public.tasks t
      where t.id = task_participants.task_id
        and t.org_id = public.current_user_org_id()
    )
  );

drop policy if exists "task_participants_insert" on public.task_participants;
create policy "task_participants_insert" on public.task_participants
  for insert to authenticated
  with check (
    exists (
      select 1
      from public.tasks t
      where t.id = task_participants.task_id
        and t.org_id = public.current_user_org_id()
    )
  );

drop policy if exists "task_participants_update" on public.task_participants;
create policy "task_participants_update" on public.task_participants
  for update to authenticated
  using (
    exists (
      select 1
      from public.tasks t
      where t.id = task_participants.task_id
        and t.org_id = public.current_user_org_id()
    )
  )
  with check (
    exists (
      select 1
      from public.tasks t
      where t.id = task_participants.task_id
        and t.org_id = public.current_user_org_id()
    )
  );

drop policy if exists "task_participants_delete" on public.task_participants;
create policy "task_participants_delete" on public.task_participants
  for delete to authenticated
  using (
    exists (
      select 1
      from public.tasks t
      where t.id = task_participants.task_id
        and t.org_id = public.current_user_org_id()
    )
  );

-- ===== 20260629170000_calendar_events.sql =====

create table if not exists public.calendar_events (
  id bigint generated by default as identity primary key,
  org_id bigint not null references public.organizations(id) on delete cascade,
  title text not null,
  event_date date not null,
  description text,
  deal_id bigint references public.deals(id) on update cascade on delete set null,
  person_id bigint references public.people(id) on update cascade on delete set null,
  contact_id bigint references public.contacts(id) on update cascade on delete set null,
  company_id bigint references public.companies(id) on update cascade on delete set null,
  organization_member_id bigint references public.organization_members(id) on update cascade on delete set null,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists calendar_events_org_id_idx
  on public.calendar_events (org_id);

create index if not exists calendar_events_event_date_idx
  on public.calendar_events (event_date);

create index if not exists calendar_events_deal_id_idx
  on public.calendar_events (deal_id)
  where deal_id is not null;

create index if not exists calendar_events_person_id_idx
  on public.calendar_events (person_id)
  where person_id is not null;

create index if not exists calendar_events_contact_id_idx
  on public.calendar_events (contact_id)
  where contact_id is not null;

alter table public.calendar_events enable row level security;

grant delete, insert, select, update on table public.calendar_events to authenticated;
grant delete, insert, references, select, trigger, truncate, update on table public.calendar_events to service_role;

drop policy if exists "calendar_events_org_scoped" on public.calendar_events;
create policy "calendar_events_org_scoped" on public.calendar_events
  for all to authenticated
  using (org_id = public.current_user_org_id())
  with check (org_id = public.current_user_org_id());

drop trigger if exists trg_calendar_events_assign_org_id on public.calendar_events;
create trigger trg_calendar_events_assign_org_id
  before insert on public.calendar_events
  for each row execute function public.trg_assign_org_id_from_session();

-- ===== 20260629180000_calendar_events_person_link.sql =====

alter table public.calendar_events
  add column if not exists person_id bigint references public.people(id) on update cascade on delete set null;

create index if not exists calendar_events_person_id_idx
  on public.calendar_events (person_id)
  where person_id is not null;

create index if not exists calendar_events_contact_id_idx
  on public.calendar_events (contact_id)
  where contact_id is not null;

-- ===== 20260629190000_calendar_events_time_and_reminder.sql =====

alter table public.calendar_events
  add column if not exists event_time time;

alter table public.calendar_events
  add column if not exists remind_before_minutes integer;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'calendar_events_remind_before_minutes_check'
      and conrelid = 'public.calendar_events'::regclass
  ) then
    alter table public.calendar_events
      add constraint calendar_events_remind_before_minutes_check
      check (remind_before_minutes is null or remind_before_minutes >= 0);
  end if;
end $$;

create index if not exists calendar_events_event_time_idx
  on public.calendar_events (event_date, event_time)
  where event_time is not null;
