-- Per-participant completion: task is done only when every tagged person has completed.

create table if not exists public.task_participants (
  id bigint generated by default as identity primary key,
  task_id bigint not null references public.tasks(id) on update cascade on delete cascade,
  person_id bigint references public.people(id) on update cascade on delete cascade,
  organization_member_id bigint references public.organization_members(id) on update cascade on delete cascade,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  constraint task_participants_person_or_member_chk check (
    (person_id is not null and organization_member_id is null)
    or (person_id is null and organization_member_id is not null)
  )
);

create unique index if not exists task_participants_task_person_uidx
  on public.task_participants (task_id, person_id)
  where person_id is not null;

create unique index if not exists task_participants_task_member_uidx
  on public.task_participants (task_id, organization_member_id)
  where organization_member_id is not null;

create index if not exists task_participants_task_id_idx
  on public.task_participants (task_id);

alter table public.task_participants enable row level security;

grant delete, insert, select, update on table public.task_participants to authenticated;
grant delete, insert, references, select, trigger, truncate, update on table public.task_participants to service_role;

drop policy if exists "task_participants_select" on public.task_participants;
create policy "task_participants_select" on public.task_participants
  for select to authenticated
  using (
    exists (
      select 1
      from public.tasks t
      where t.id = task_participants.task_id
        and t.org_id = public.current_user_org_id()
    )
  );

drop policy if exists "task_participants_insert" on public.task_participants;
create policy "task_participants_insert" on public.task_participants
  for insert to authenticated
  with check (
    exists (
      select 1
      from public.tasks t
      where t.id = task_participants.task_id
        and t.org_id = public.current_user_org_id()
    )
  );

drop policy if exists "task_participants_update" on public.task_participants;
create policy "task_participants_update" on public.task_participants
  for update to authenticated
  using (
    exists (
      select 1
      from public.tasks t
      where t.id = task_participants.task_id
        and t.org_id = public.current_user_org_id()
    )
  )
  with check (
    exists (
      select 1
      from public.tasks t
      where t.id = task_participants.task_id
        and t.org_id = public.current_user_org_id()
    )
  );

drop policy if exists "task_participants_delete" on public.task_participants;
create policy "task_participants_delete" on public.task_participants
  for delete to authenticated
  using (
    exists (
      select 1
      from public.tasks t
      where t.id = task_participants.task_id
        and t.org_id = public.current_user_org_id()
    )
  );
