-- Website uptime monitoring for client/lead company URLs.

create table if not exists public.monitored_websites (
  id bigint generated by default as identity primary key,
  org_id bigint not null references public.organizations (id) on delete cascade,
  company_id bigint references public.companies (id) on update cascade on delete set null,
  contact_id bigint references public.contacts (id) on update cascade on delete set null,
  url text not null,
  display_name text,
  source text not null default 'company'
    check (source in ('company', 'contact', 'manual')),
  is_enabled boolean not null default true,
  slow_threshold_ms integer not null default 3000
    check (slow_threshold_ms > 0),
  check_interval_minutes integer not null default 5
    check (check_interval_minutes >= 1),
  last_status text not null default 'unknown'
    check (last_status in ('up', 'slow', 'down', 'unknown')),
  last_response_ms integer,
  last_http_status integer,
  last_checked_at timestamptz,
  last_error text,
  ssl_expires_at timestamptz,
  ssl_days_remaining integer,
  dns_ip text,
  dns_nameservers text[] not null default '{}',
  dns_mx text[] not null default '{}',
  hosting_provider text,
  hosting_confidence text
    check (hosting_confidence is null or hosting_confidence in ('low', 'medium', 'high')),
  tech_stack text[] not null default '{}',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (org_id, url)
);

create index if not exists monitored_websites_org_id_idx
  on public.monitored_websites (org_id);

create index if not exists monitored_websites_company_id_idx
  on public.monitored_websites (company_id)
  where company_id is not null;

create index if not exists monitored_websites_last_status_idx
  on public.monitored_websites (org_id, last_status);

create index if not exists monitored_websites_enabled_due_idx
  on public.monitored_websites (is_enabled, last_checked_at)
  where is_enabled = true;

create table if not exists public.website_checks (
  id bigint generated by default as identity primary key,
  org_id bigint not null references public.organizations (id) on delete cascade,
  monitored_website_id bigint not null references public.monitored_websites (id) on delete cascade,
  checked_at timestamptz not null default now(),
  status text not null check (status in ('up', 'slow', 'down')),
  response_ms integer,
  http_status integer,
  error_message text,
  ssl_days_remaining integer,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists website_checks_site_checked_idx
  on public.website_checks (monitored_website_id, checked_at desc);

create index if not exists website_checks_org_checked_idx
  on public.website_checks (org_id, checked_at desc);

alter table public.monitored_websites enable row level security;
alter table public.website_checks enable row level security;

grant delete, insert, select, update on table public.monitored_websites to authenticated;
grant delete, insert, references, select, trigger, truncate, update on table public.monitored_websites to service_role;

grant delete, insert, select, update on table public.website_checks to authenticated;
grant delete, insert, references, select, trigger, truncate, update on table public.website_checks to service_role;

drop policy if exists "monitored_websites_org_scoped" on public.monitored_websites;
create policy "monitored_websites_org_scoped" on public.monitored_websites
  for all to authenticated
  using (org_id = public.current_user_org_id())
  with check (org_id = public.current_user_org_id());

drop policy if exists "website_checks_org_scoped" on public.website_checks;
create policy "website_checks_org_scoped" on public.website_checks
  for all to authenticated
  using (org_id = public.current_user_org_id())
  with check (org_id = public.current_user_org_id());

drop trigger if exists trg_monitored_websites_assign_org on public.monitored_websites;
create trigger trg_monitored_websites_assign_org
  before insert on public.monitored_websites
  for each row execute function public.trg_assign_org_id_from_session();

drop trigger if exists trg_website_checks_assign_org on public.website_checks;
create trigger trg_website_checks_assign_org
  before insert on public.website_checks
  for each row execute function public.trg_assign_org_id_from_session();

create or replace function public.normalize_website_monitor_url(raw_url text)
returns text
language plpgsql
immutable
as $$
declare
  trimmed text;
  candidate text;
begin
  trimmed := nullif(trim(both from coalesce(raw_url, '')), '');
  if trimmed is null then
    return null;
  end if;

  candidate := trimmed;
  if candidate !~* '^https?://' then
    candidate := 'https://' || candidate;
  end if;

  if candidate !~* '^https?://[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)+(/.*)?$' then
    return null;
  end if;

  return trim(trailing '/' from candidate);
end;
$$;

create or replace function public.sync_monitored_websites_for_org(target_org_id bigint)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  upserted_count integer := 0;
begin
  insert into public.monitored_websites (
    org_id,
    company_id,
    url,
    display_name,
    source,
    is_enabled
  )
  select distinct on (c.org_id, public.normalize_website_monitor_url(c.website))
    c.org_id,
    c.id,
    public.normalize_website_monitor_url(c.website),
    c.name,
    'company',
    true
  from public.companies c
  where c.org_id = target_org_id
    and public.normalize_website_monitor_url(c.website) is not null
  order by c.org_id, public.normalize_website_monitor_url(c.website), c.id
  on conflict (org_id, url) do update
  set
    company_id = excluded.company_id,
    display_name = coalesce(excluded.display_name, public.monitored_websites.display_name),
    source = 'company',
    is_enabled = true,
    updated_at = now();

  get diagnostics upserted_count = row_count;

  update public.monitored_websites mw
  set
    is_enabled = false,
    updated_at = now()
  where mw.org_id = target_org_id
    and mw.source = 'company'
    and mw.company_id is not null
    and not exists (
      select 1
      from public.companies c
      where c.id = mw.company_id
        and public.normalize_website_monitor_url(c.website) = mw.url
        and c.org_id = target_org_id
    );

  return upserted_count;
end;
$$;

grant execute on function public.sync_monitored_websites_for_org(bigint) to authenticated;
grant execute on function public.sync_monitored_websites_for_org(bigint) to service_role;

create or replace function public.trg_company_sync_monitored_website()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_url text;
  previous_url text;
  url_changed boolean := false;
begin
  normalized_url := public.normalize_website_monitor_url(new.website);

  if tg_op = 'UPDATE' then
    previous_url := public.normalize_website_monitor_url(old.website);
    url_changed := previous_url is distinct from normalized_url;
  end if;

  if normalized_url is null then
    update public.monitored_websites
    set is_enabled = false, updated_at = now()
    where company_id = new.id and org_id = new.org_id;
    return new;
  end if;

  insert into public.monitored_websites (
    org_id,
    company_id,
    url,
    display_name,
    source,
    is_enabled
  )
  values (
    new.org_id,
    new.id,
    normalized_url,
    new.name,
    'company',
    true
  )
  on conflict (org_id, url) do update
  set
    company_id = excluded.company_id,
    display_name = excluded.display_name,
    is_enabled = true,
    updated_at = now();

  update public.monitored_websites
  set
    is_enabled = false,
    updated_at = now()
  where org_id = new.org_id
    and company_id = new.id
    and source = 'company'
    and url is distinct from normalized_url;

  if tg_op = 'INSERT' or url_changed then
    update public.monitored_websites
    set
      last_status = 'unknown',
      last_response_ms = null,
      last_http_status = null,
      last_checked_at = null,
      last_error = null,
      ssl_expires_at = null,
      ssl_days_remaining = null,
      dns_ip = null,
      dns_nameservers = '{}',
      dns_mx = '{}',
      hosting_provider = null,
      hosting_confidence = null,
      tech_stack = '{}',
      metadata = '{}'::jsonb,
      updated_at = now()
    where org_id = new.org_id
      and url = normalized_url
      and company_id = new.id;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_companies_sync_monitored_website on public.companies;
create trigger trg_companies_sync_monitored_website
  after insert or update of website, name on public.companies
  for each row
  when (new.website is not null and trim(new.website) <> '')
  execute function public.trg_company_sync_monitored_website();

create or replace view public.monitored_websites_summary
with (security_invoker = true)
as
select
  mw.*,
  c.name as company_name,
  (
    select round(
      100.0 * count(*) filter (where wc.status in ('up', 'slow'))
      / nullif(count(*), 0),
      1
    )
    from public.website_checks wc
    where wc.monitored_website_id = mw.id
      and wc.checked_at >= now() - interval '7 days'
  ) as uptime_pct_7d,
  (
    select round(avg(wc.response_ms)::numeric, 0)
    from public.website_checks wc
    where wc.monitored_website_id = mw.id
      and wc.checked_at >= now() - interval '7 days'
      and wc.response_ms is not null
  ) as avg_response_ms_7d
from public.monitored_websites mw
left join public.companies c on c.id = mw.company_id;

grant select on public.monitored_websites_summary to authenticated;
grant select on public.monitored_websites_summary to service_role;

comment on table public.monitored_websites is
  'Client/lead websites monitored for uptime and marketing outreach signals.';
comment on table public.website_checks is
  'Historical uptime checks for monitored websites.';

do $$
declare
  org_row record;
begin
  for org_row in select id from public.organizations loop
    perform public.sync_monitored_websites_for_org(org_row.id);
  end loop;
end;
$$;
