-- Task people assignment: assignees, collaborators, junction table, and tag notifications

alter table public.tasks
  add column if not exists assignee_person_ids bigint[] not null default '{}',
  add column if not exists collaborator_person_ids bigint[] not null default '{}';

create index if not exists tasks_assignee_person_ids_idx
  on public.tasks using gin (assignee_person_ids);

create index if not exists tasks_collaborator_person_ids_idx
  on public.tasks using gin (collaborator_person_ids);

create table if not exists public.task_assignees (
  id bigint generated by default as identity primary key,
  task_id bigint not null references public.tasks(id) on update cascade on delete cascade,
  person_id bigint not null references public.people(id) on update cascade on delete restrict,
  role text not null default 'collaborator'
    check (role in ('assignee', 'collaborator', 'watcher')),
  created_at timestamptz not null default now(),
  unique (task_id, person_id)
);

create index if not exists task_assignees_task_id_idx on public.task_assignees(task_id);
create index if not exists task_assignees_person_id_idx on public.task_assignees(person_id);

alter table public.task_assignees enable row level security;

grant delete, insert, select, update on table public.task_assignees to authenticated;
grant delete, insert, references, select, trigger, truncate, update on table public.task_assignees to service_role;

create policy "task_assignees_select" on public.task_assignees
  for select to authenticated
  using (
    exists (
      select 1
      from public.tasks t
      where t.id = task_assignees.task_id
        and t.org_id = public.current_user_org_id()
    )
  );

create policy "task_assignees_insert" on public.task_assignees
  for insert to authenticated
  with check (
    exists (
      select 1
      from public.tasks t
      where t.id = task_assignees.task_id
        and t.org_id = public.current_user_org_id()
    )
  );

create policy "task_assignees_update" on public.task_assignees
  for update to authenticated
  using (
    exists (
      select 1
      from public.tasks t
      where t.id = task_assignees.task_id
        and t.org_id = public.current_user_org_id()
    )
  )
  with check (
    exists (
      select 1
      from public.tasks t
      where t.id = task_assignees.task_id
        and t.org_id = public.current_user_org_id()
    )
  );

create policy "task_assignees_delete" on public.task_assignees
  for delete to authenticated
  using (
    exists (
      select 1
      from public.tasks t
      where t.id = task_assignees.task_id
        and t.org_id = public.current_user_org_id()
    )
  );

create table if not exists public.task_tag_notifications (
  id bigint generated by default as identity primary key,
  task_id bigint not null references public.tasks(id) on update cascade on delete cascade,
  person_id bigint not null references public.people(id) on update cascade on delete cascade,
  recipient_organization_member_id bigint not null
    references public.organization_members(id) on update cascade on delete cascade,
  read_at timestamptz,
  created_at timestamptz not null default now(),
  unique (task_id, person_id, recipient_organization_member_id)
);

create index if not exists task_tag_notifications_recipient_unread_idx
  on public.task_tag_notifications (recipient_organization_member_id)
  where read_at is null;

alter table public.task_tag_notifications enable row level security;

grant delete, insert, select, update on table public.task_tag_notifications to authenticated;
grant delete, insert, references, select, trigger, truncate, update on table public.task_tag_notifications to service_role;

create policy "task_tag_notifications_select" on public.task_tag_notifications
  for select to authenticated
  using (
    recipient_organization_member_id in (
      select om.id
      from public.organization_members om
      where om.user_id = auth.uid()
    )
  );

create policy "task_tag_notifications_update" on public.task_tag_notifications
  for update to authenticated
  using (
    recipient_organization_member_id in (
      select om.id
      from public.organization_members om
      where om.user_id = auth.uid()
    )
  )
  with check (
    recipient_organization_member_id in (
      select om.id
      from public.organization_members om
      where om.user_id = auth.uid()
    )
  );

create or replace function public.trg_task_assignee_notify()
returns trigger
language plpgsql
security definer
set search_path = public
as $fn$
declare
  v_person_email text;
  v_org_id bigint;
  v_member_id bigint;
begin
  select p.email, t.org_id
  into v_person_email, v_org_id
  from public.people p
  join public.tasks t on t.id = new.task_id
  where p.id = new.person_id;

  if v_person_email is null or btrim(v_person_email) = '' then
    return new;
  end if;

  select om.id
  into v_member_id
  from public.organization_members om
  where om.org_id = v_org_id
    and lower(btrim(om.email)) = lower(btrim(v_person_email))
    and coalesce(om.disabled, false) = false
  limit 1;

  if v_member_id is not null then
    insert into public.task_tag_notifications (
      task_id,
      person_id,
      recipient_organization_member_id
    )
    values (new.task_id, new.person_id, v_member_id)
    on conflict (task_id, person_id, recipient_organization_member_id) do nothing;
  end if;

  return new;
end;
$fn$;

drop trigger if exists trg_task_assignee_notify on public.task_assignees;

create trigger trg_task_assignee_notify
  after insert on public.task_assignees
  for each row
  execute function public.trg_task_assignee_notify();
