-- Hostinger domain portfolio cache and per-org API credentials.

create table if not exists public.organization_hostinger_settings (
  org_id bigint primary key references public.organizations (id) on delete cascade,
  api_token_encrypted text,
  last_synced_at timestamptz,
  last_sync_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.organization_hostinger_settings is
  'Per-org Hostinger API token (encrypted) and sync metadata.';

create table if not exists public.hostinger_domains (
  id bigint generated by default as identity primary key,
  org_id bigint not null references public.organizations (id) on delete cascade,
  hostinger_id integer,
  domain text not null,
  domain_type text,
  status text not null default 'active',
  expires_at timestamptz,
  registered_at timestamptz,
  is_locked boolean,
  is_privacy_protected boolean,
  company_id bigint references public.companies (id) on update cascade on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  synced_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (org_id, domain)
);

create index if not exists hostinger_domains_org_id_idx
  on public.hostinger_domains (org_id);

create index if not exists hostinger_domains_expires_at_idx
  on public.hostinger_domains (org_id, expires_at);

create index if not exists hostinger_domains_company_id_idx
  on public.hostinger_domains (company_id)
  where company_id is not null;

create index if not exists hostinger_domains_status_idx
  on public.hostinger_domains (org_id, status);

alter table public.organization_hostinger_settings enable row level security;
alter table public.hostinger_domains enable row level security;

grant select, insert, update, delete on table public.organization_hostinger_settings to authenticated;
grant all on table public.organization_hostinger_settings to service_role;

grant select, insert, update, delete on table public.hostinger_domains to authenticated;
grant all on table public.hostinger_domains to service_role;

drop policy if exists "organization_hostinger_settings_org_scoped"
  on public.organization_hostinger_settings;
create policy "organization_hostinger_settings_org_scoped"
  on public.organization_hostinger_settings
  for all to authenticated
  using (org_id = public.current_user_org_id())
  with check (org_id = public.current_user_org_id());

drop policy if exists "hostinger_domains_org_scoped" on public.hostinger_domains;
create policy "hostinger_domains_org_scoped" on public.hostinger_domains
  for all to authenticated
  using (org_id = public.current_user_org_id())
  with check (org_id = public.current_user_org_id());

drop trigger if exists trg_hostinger_domains_assign_org on public.hostinger_domains;
create trigger trg_hostinger_domains_assign_org
  before insert on public.hostinger_domains
  for each row execute function public.trg_assign_org_id_from_session();

create or replace function public.encrypt_hostinger_api_token(p_token text, p_key text)
returns text
language plpgsql
immutable
set search_path = public, extensions
as $$
begin
  if p_token is null or btrim(p_token) = '' then
    return null;
  end if;
  if p_key is null or btrim(p_key) = '' then
    raise exception 'PGCRYPTO_KEY is required to encrypt Hostinger API token';
  end if;
  return encode(extensions.pgp_sym_encrypt(btrim(p_token), btrim(p_key)), 'base64');
end;
$$;

create or replace function public.decrypt_hostinger_api_token(p_encrypted text, p_key text)
returns text
language plpgsql
immutable
set search_path = public, extensions
as $$
begin
  if p_encrypted is null or btrim(p_encrypted) = '' then
    return null;
  end if;
  if p_key is null or btrim(p_key) = '' then
    raise exception 'PGCRYPTO_KEY is required to decrypt Hostinger API token';
  end if;
  return extensions.pgp_sym_decrypt(decode(btrim(p_encrypted), 'base64'), btrim(p_key));
exception
  when others then
    return null;
end;
$$;

create or replace function public.get_hostinger_api_token(p_org_id bigint, p_key text)
returns text
language plpgsql
stable
security definer
set search_path = public, extensions
as $$
declare
  enc text;
begin
  select api_token_encrypted
  into enc
  from public.organization_hostinger_settings
  where org_id = p_org_id;

  if enc is not null and btrim(enc) <> '' then
    return public.decrypt_hostinger_api_token(enc, p_key);
  end if;

  return null;
end;
$$;

create or replace function public.set_hostinger_api_token(p_org_id bigint, p_token text, p_key text)
returns void
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  insert into public.organization_hostinger_settings (org_id, api_token_encrypted, updated_at)
  values (
    p_org_id,
    public.encrypt_hostinger_api_token(p_token, p_key),
    now()
  )
  on conflict (org_id) do update
  set
    api_token_encrypted = excluded.api_token_encrypted,
    updated_at = now();
end;
$$;

revoke all on function public.encrypt_hostinger_api_token(text, text) from public;
revoke all on function public.decrypt_hostinger_api_token(text, text) from public;
revoke all on function public.get_hostinger_api_token(bigint, text) from public, authenticated;
revoke all on function public.set_hostinger_api_token(bigint, text, text) from public, authenticated;

grant execute on function public.get_hostinger_api_token(bigint, text) to service_role;
grant execute on function public.set_hostinger_api_token(bigint, text, text) to service_role;

create or replace view public.hostinger_domains_summary
with (security_invoker = true)
as
select
  hd.*,
  c.name as company_name
from public.hostinger_domains hd
left join public.companies c on c.id = hd.company_id;

grant select on public.hostinger_domains_summary to authenticated;
grant select on public.hostinger_domains_summary to service_role;

comment on table public.hostinger_domains is
  'Cached Hostinger domain portfolio synced from the Hostinger API.';
