-- Foundation for complete Hours + Payroll + Loans flow

alter table public.people
  add column if not exists employee_status text,
  add column if not exists payment_method text,
  add column if not exists biweekly_salary_amount numeric(12,2),
  add column if not exists lunch_break_deducted boolean not null default true,
  add column if not exists default_lunch_minutes integer not null default 30,
  add column if not exists paid_day_hours numeric(8,2) not null default 8,
  add column if not exists working_days_per_week integer not null default 6,
  add column if not exists off_days_paid boolean not null default false,
  add column if not exists holidays_paid boolean not null default true,
  add column if not exists sick_days_paid boolean not null default false,
  add column if not exists vacation_days_paid boolean not null default false,
  add column if not exists sick_balance_days numeric(8,2) not null default 0,
  add column if not exists vacation_balance_days numeric(8,2) not null default 0,
  add column if not exists approver_roles text[] default array['owner','admin','accountant'];

update public.people
set employee_status = coalesce(employee_status, status);

update public.people
set compensation_type = 'monthly_salary',
    monthly_salary_amount = coalesce(monthly_salary_amount, salary_rate, 0)
where compensation_type = 'fixed_salary';

alter table public.people
  drop constraint if exists people_employee_status_check;
alter table public.people
  add constraint people_employee_status_check
  check (employee_status in ('active', 'inactive'));

alter table public.people
  drop constraint if exists people_payment_method_check;
alter table public.people
  add constraint people_payment_method_check
  check (payment_method in ('cash', 'check', 'zelle', 'bank_deposit'));

alter table public.people
  drop constraint if exists people_compensation_type_check;
alter table public.people
  add constraint people_compensation_type_check
  check (compensation_type in ('hourly', 'weekly_salary', 'biweekly_salary', 'monthly_salary', 'commission'));

alter table public.time_entries
  alter column project_id drop not null;

alter table public.time_entries
  add column if not exists day_type text not null default 'worked_day',
  add column if not exists lunch_minutes integer,
  add column if not exists break_minutes integer,
  add column if not exists worked_hours_raw numeric(8,2),
  add column if not exists payable_hours numeric(8,2),
  add column if not exists payroll_run_id bigint;

update public.time_entries
set worked_hours_raw = coalesce(worked_hours_raw, hours + (coalesce(lunch_minutes, break_minutes, 0)::numeric / 60)),
    payable_hours = coalesce(payable_hours, hours),
    day_type = coalesce(day_type, 'worked_day');

alter table public.time_entries
  drop constraint if exists time_entries_day_type_check;

alter table public.time_entries
  add constraint time_entries_day_type_check
  check (day_type in ('worked_day', 'holiday', 'sick_day', 'vacation_day', 'day_off', 'unpaid_leave'));

alter table public.time_entries
  drop constraint if exists time_entries_status_check;

alter table public.time_entries
  add constraint time_entries_status_check
  check (status in ('draft', 'submitted', 'approved', 'rejected', 'included_in_payroll', 'paid'));

create table if not exists public.payroll_runs (
  id bigint generated by default as identity primary key,
  org_id bigint not null default 1,
  category text not null check (category in ('hourly', 'salaried', 'subcontractor', 'sales_commissions', 'mixed')),
  pay_schedule text not null check (pay_schedule in ('weekly', 'biweekly', 'semimonthly', 'monthly')),
  pay_period_start date not null,
  pay_period_end date not null,
  payday date not null,
  status text not null default 'draft' check (status in ('draft', 'reviewed', 'approved', 'paid', 'cancelled')),
  created_by text,
  created_at timestamp with time zone not null default now(),
  approved_at timestamp with time zone,
  paid_at timestamp with time zone,
  notes text,
  check (pay_period_start <= pay_period_end)
);

alter table public.time_entries
  drop constraint if exists time_entries_payroll_run_id_fkey;

alter table public.time_entries
  add constraint time_entries_payroll_run_id_fkey
  foreign key (payroll_run_id) references public.payroll_runs(id)
  on update cascade on delete set null
  deferrable initially deferred;

create table if not exists public.payroll_run_lines (
  id bigint generated by default as identity primary key,
  payroll_run_id bigint not null references public.payroll_runs(id) on update cascade on delete cascade,
  employee_id bigint not null references public.people(id) on update cascade on delete restrict,
  compensation_type text not null check (compensation_type in ('hourly', 'weekly_salary', 'biweekly_salary', 'monthly_salary')),
  payment_method text not null check (payment_method in ('cash', 'check', 'zelle', 'bank_deposit')),
  regular_hours numeric(8,2),
  overtime_hours numeric(8,2),
  paid_leave_hours numeric(8,2),
  base_salary_amount numeric(14,2),
  unpaid_absence_deduction numeric(14,2) default 0,
  loan_deductions numeric(14,2) default 0,
  other_deductions numeric(14,2) default 0,
  gross_pay numeric(14,2) not null default 0,
  total_deductions numeric(14,2) not null default 0,
  net_pay numeric(14,2) not null default 0,
  payment_reference text,
  payment_notes text,
  created_at timestamp with time zone not null default now()
);

create table if not exists public.employee_loans (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references public.people(id) on update cascade on delete restrict,
  loan_date date not null,
  original_amount numeric(14,2) not null,
  remaining_balance numeric(14,2) not null,
  fixed_installment_amount numeric(14,2) not null,
  deduction_mode text not null default 'fixed_installment',
  active boolean not null default true,
  paused boolean not null default false,
  start_next_payroll boolean not null default true,
  notes text,
  reason text,
  created_at timestamp with time zone not null default now()
);

create table if not exists public.employee_loan_deductions (
  id bigint generated by default as identity primary key,
  loan_id bigint not null references public.employee_loans(id) on update cascade on delete cascade,
  payroll_run_id bigint references public.payroll_runs(id) on update cascade on delete set null,
  deduction_date date not null,
  scheduled_amount numeric(14,2) not null,
  deducted_amount numeric(14,2) not null,
  remaining_balance_after numeric(14,2) not null,
  notes text,
  created_at timestamp with time zone not null default now()
);

create index if not exists payroll_runs_status_idx on public.payroll_runs(status);
create index if not exists payroll_runs_period_idx on public.payroll_runs(pay_period_start, pay_period_end);
create index if not exists payroll_run_lines_run_idx on public.payroll_run_lines(payroll_run_id);
create index if not exists payroll_run_lines_employee_idx on public.payroll_run_lines(employee_id);
create index if not exists employee_loans_employee_idx on public.employee_loans(employee_id);
create index if not exists employee_loans_active_idx on public.employee_loans(active, paused);
create index if not exists employee_loan_deductions_loan_idx on public.employee_loan_deductions(loan_id);

alter table public.payroll_runs enable row level security;
alter table public.payroll_run_lines enable row level security;
alter table public.employee_loans enable row level security;
alter table public.employee_loan_deductions enable row level security;

grant delete, insert, select, update on table public.payroll_runs to authenticated;
grant delete, insert, select, update on table public.payroll_run_lines to authenticated;
grant delete, insert, select, update on table public.employee_loans to authenticated;
grant delete, insert, select, update on table public.employee_loan_deductions to authenticated;

grant delete, insert, references, select, trigger, truncate, update on table public.payroll_runs to service_role;
grant delete, insert, references, select, trigger, truncate, update on table public.payroll_run_lines to service_role;
grant delete, insert, references, select, trigger, truncate, update on table public.employee_loans to service_role;
grant delete, insert, references, select, trigger, truncate, update on table public.employee_loan_deductions to service_role;

create policy "Payroll runs insert" on public.payroll_runs as permissive for insert to authenticated with check (true);
create policy "Payroll runs select" on public.payroll_runs as permissive for select to authenticated using (true);
create policy "Payroll runs update" on public.payroll_runs as permissive for update to authenticated using (true) with check (true);
create policy "Payroll runs delete" on public.payroll_runs as permissive for delete to authenticated using (true);

create policy "Payroll run lines insert" on public.payroll_run_lines as permissive for insert to authenticated with check (true);
create policy "Payroll run lines select" on public.payroll_run_lines as permissive for select to authenticated using (true);
create policy "Payroll run lines update" on public.payroll_run_lines as permissive for update to authenticated using (true) with check (true);
create policy "Payroll run lines delete" on public.payroll_run_lines as permissive for delete to authenticated using (true);

create policy "Employee loans insert" on public.employee_loans as permissive for insert to authenticated with check (true);
create policy "Employee loans select" on public.employee_loans as permissive for select to authenticated using (true);
create policy "Employee loans update" on public.employee_loans as permissive for update to authenticated using (true) with check (true);
create policy "Employee loans delete" on public.employee_loans as permissive for delete to authenticated using (true);

create policy "Employee loan deductions insert" on public.employee_loan_deductions as permissive for insert to authenticated with check (true);
create policy "Employee loan deductions select" on public.employee_loan_deductions as permissive for select to authenticated using (true);
create policy "Employee loan deductions update" on public.employee_loan_deductions as permissive for update to authenticated using (true) with check (true);
create policy "Employee loan deductions delete" on public.employee_loan_deductions as permissive for delete to authenticated using (true);

create or replace function public.generate_payroll_run(p_payroll_run_id bigint)
returns integer
language plpgsql
security invoker
as $$
declare
  v_run public.payroll_runs%rowtype;
  v_inserted integer := 0;
  v_rowcount integer := 0;
  v_expected_days integer := 0;
begin
  select * into v_run from public.payroll_runs where id = p_payroll_run_id;
  if v_run is null then
    raise exception 'Payroll run % not found', p_payroll_run_id;
  end if;

  v_expected_days := greatest(1, (v_run.pay_period_end - v_run.pay_period_start + 1));

  insert into public.payroll_run_lines (
    payroll_run_id,
    employee_id,
    compensation_type,
    payment_method,
    regular_hours,
    overtime_hours,
    paid_leave_hours,
    base_salary_amount,
    unpaid_absence_deduction,
    gross_pay,
    total_deductions,
    net_pay,
    payment_notes
  )
  select
    v_run.id,
    p.id,
    p.compensation_type,
    coalesce(p.payment_method, 'bank_deposit'),
    case when p.compensation_type = 'hourly' then coalesce(sum(te.regular_hours), 0) else null end,
    case when p.compensation_type = 'hourly' then coalesce(sum(te.overtime_hours), 0) else null end,
    case when p.compensation_type = 'hourly' then coalesce(sum(
      case when te.day_type in ('holiday', 'sick_day', 'vacation_day', 'day_off') then coalesce(te.payable_hours, 0) else 0 end
    ), 0) else null end,
    case
      when p.compensation_type = 'weekly_salary' then coalesce(p.weekly_salary_amount, 0)
      when p.compensation_type = 'biweekly_salary' then coalesce(p.biweekly_salary_amount, 0)
      when p.compensation_type = 'monthly_salary' then coalesce(p.monthly_salary_amount, 0)
      else null
    end,
    0,
    round(
      case
        when p.compensation_type = 'hourly' then
          coalesce(sum(te.regular_hours), 0) * coalesce(p.hourly_rate, 0)
          + coalesce(sum(te.overtime_hours), 0) * coalesce(p.hourly_rate, 0) * coalesce(p.overtime_rate_multiplier, 1.5)
          + coalesce(sum(case when te.day_type in ('holiday', 'sick_day', 'vacation_day', 'day_off') then coalesce(te.payable_hours, 0) else 0 end), 0) * coalesce(p.hourly_rate, 0)
        when p.compensation_type = 'weekly_salary' then coalesce(p.weekly_salary_amount, 0)
        when p.compensation_type = 'biweekly_salary' then coalesce(p.biweekly_salary_amount, 0)
        when p.compensation_type = 'monthly_salary' then coalesce(p.monthly_salary_amount, 0)
        else 0
      end,
      2
    ),
    0,
    round(
      case
        when p.compensation_type = 'hourly' then
          coalesce(sum(te.regular_hours), 0) * coalesce(p.hourly_rate, 0)
          + coalesce(sum(te.overtime_hours), 0) * coalesce(p.hourly_rate, 0) * coalesce(p.overtime_rate_multiplier, 1.5)
          + coalesce(sum(case when te.day_type in ('holiday', 'sick_day', 'vacation_day', 'day_off') then coalesce(te.payable_hours, 0) else 0 end), 0) * coalesce(p.hourly_rate, 0)
        when p.compensation_type = 'weekly_salary' then coalesce(p.weekly_salary_amount, 0)
        when p.compensation_type = 'biweekly_salary' then coalesce(p.biweekly_salary_amount, 0)
        when p.compensation_type = 'monthly_salary' then coalesce(p.monthly_salary_amount, 0)
        else 0
      end,
      2
    ),
    'Generated by payroll run engine'
  from public.people p
  left join public.time_entries te on te.person_id = p.id
    and te.status = 'approved'
    and te.date between v_run.pay_period_start and v_run.pay_period_end
  where p.org_id = v_run.org_id
    and p.employee_status = 'active'
    and p.compensation_type in ('hourly', 'weekly_salary', 'biweekly_salary', 'monthly_salary')
    and not exists (
      select 1
      from public.payroll_run_lines prl
      where prl.payroll_run_id = v_run.id
        and prl.employee_id = p.id
    )
  group by p.id;

  get diagnostics v_rowcount = row_count;
  v_inserted := v_inserted + v_rowcount;

  update public.time_entries te
  set status = 'included_in_payroll',
      included_in_payroll = true,
      payroll_run_id = v_run.id
  where te.status = 'approved'
    and te.date between v_run.pay_period_start and v_run.pay_period_end
    and te.person_id in (
      select prl.employee_id from public.payroll_run_lines prl where prl.payroll_run_id = v_run.id
    );

  return v_inserted;
end;
$$;

create or replace function public.mark_payroll_run_entries_paid()
returns trigger
language plpgsql
as $$
begin
  if new.status = 'paid' and old.status is distinct from 'paid' then
    update public.time_entries te
    set status = 'paid',
        included_in_payroll = true,
        payroll_run_id = new.id
    where te.payroll_run_id = new.id;
  end if;

  return new;
end;
$$;

drop trigger if exists payroll_runs_mark_entries_paid on public.payroll_runs;
create trigger payroll_runs_mark_entries_paid
after update of status on public.payroll_runs
for each row
execute function public.mark_payroll_run_entries_paid();
