-- Custom calendar reminders (not tasks): follow-ups, notes, and standalone events.

create table if not exists public.calendar_events (
  id bigint generated by default as identity primary key,
  org_id bigint not null references public.organizations(id) on delete cascade,
  title text not null,
  event_date date not null,
  description text,
  deal_id bigint references public.deals(id) on update cascade on delete set null,
  person_id bigint references public.people(id) on update cascade on delete set null,
  contact_id bigint references public.contacts(id) on update cascade on delete set null,
  company_id bigint references public.companies(id) on update cascade on delete set null,
  organization_member_id bigint references public.organization_members(id) on update cascade on delete set null,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists calendar_events_org_id_idx
  on public.calendar_events (org_id);

create index if not exists calendar_events_event_date_idx
  on public.calendar_events (event_date);

create index if not exists calendar_events_deal_id_idx
  on public.calendar_events (deal_id)
  where deal_id is not null;

create index if not exists calendar_events_person_id_idx
  on public.calendar_events (person_id)
  where person_id is not null;

create index if not exists calendar_events_contact_id_idx
  on public.calendar_events (contact_id)
  where contact_id is not null;

alter table public.calendar_events enable row level security;

grant delete, insert, select, update on table public.calendar_events to authenticated;
grant delete, insert, references, select, trigger, truncate, update on table public.calendar_events to service_role;

drop policy if exists "calendar_events_org_scoped" on public.calendar_events;
create policy "calendar_events_org_scoped" on public.calendar_events
  for all to authenticated
  using (org_id = public.current_user_org_id())
  with check (org_id = public.current_user_org_id());

drop trigger if exists trg_calendar_events_assign_org_id on public.calendar_events;
create trigger trg_calendar_events_assign_org_id
  before insert on public.calendar_events
  for each row execute function public.trg_assign_org_id_from_session();
