-- Website monitor v2: deep checks, changes, alerts, multi-path, manual URLs.

alter table public.monitored_websites
  add column if not exists page_title text,
  add column if not exists domain_name text,
  add column if not exists check_paths text[] not null default '{/}',
  add column if not exists notes text,
  add column if not exists deal_id bigint references public.deals (id) on update cascade on delete set null,
  add column if not exists alert_on_down boolean not null default true,
  add column if not exists alert_on_slow boolean not null default false,
  add column if not exists alert_on_ssl boolean not null default true,
  add column if not exists last_alert_sent_at timestamptz,
  add column if not exists last_alert_status text;

create index if not exists monitored_websites_deal_id_idx
  on public.monitored_websites (deal_id)
  where deal_id is not null;

create index if not exists monitored_websites_domain_name_idx
  on public.monitored_websites (org_id, domain_name);

create index if not exists monitored_websites_hosting_provider_idx
  on public.monitored_websites (org_id, hosting_provider);

create table if not exists public.website_monitor_changes (
  id bigint generated by default as identity primary key,
  org_id bigint not null references public.organizations (id) on delete cascade,
  monitored_website_id bigint not null references public.monitored_websites (id) on delete cascade,
  detected_at timestamptz not null default now(),
  change_type text not null
    check (change_type in (
      'status', 'hosting', 'tech_stack', 'ssl', 'page_title', 'dns', 'response_time'
    )),
  previous_value text,
  new_value text,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists website_monitor_changes_site_idx
  on public.website_monitor_changes (monitored_website_id, detected_at desc);

alter table public.website_monitor_changes enable row level security;

grant select on table public.website_monitor_changes to authenticated;
grant delete, insert, references, select, trigger, truncate, update
  on table public.website_monitor_changes to service_role;

drop policy if exists "website_monitor_changes_org_scoped" on public.website_monitor_changes;
create policy "website_monitor_changes_org_scoped" on public.website_monitor_changes
  for all to authenticated
  using (org_id = public.current_user_org_id())
  with check (org_id = public.current_user_org_id());

drop trigger if exists trg_website_monitor_changes_assign_org on public.website_monitor_changes;
create trigger trg_website_monitor_changes_assign_org
  before insert on public.website_monitor_changes
  for each row execute function public.trg_assign_org_id_from_session();

create or replace function public.extract_domain_from_url(raw_url text)
returns text
language sql
immutable
as $$
  select nullif(
    lower(
      regexp_replace(
        regexp_replace(
          trim(both from coalesce(raw_url, '')),
          '^https?://(www\.)?',
          '',
          'i'
        ),
        '/.*$',
        ''
      )
    ),
    ''
  );
$$;

update public.monitored_websites
set domain_name = public.extract_domain_from_url(url)
where domain_name is null and url is not null;

drop view if exists public.monitored_websites_summary;

create view public.monitored_websites_summary
with (security_invoker = true)
as
select
  mw.*,
  c.name as company_name,
  c.sector as company_sector,
  coalesce(mw.domain_name, public.extract_domain_from_url(mw.url)) as resolved_domain,
  (
    select round(
      100.0 * count(*) filter (where wc.status in ('up', 'slow'))
      / nullif(count(*), 0),
      1
    )
    from public.website_checks wc
    where wc.monitored_website_id = mw.id
      and wc.checked_at >= now() - interval '7 days'
  ) as uptime_pct_7d,
  (
    select round(avg(wc.response_ms)::numeric, 0)
    from public.website_checks wc
    where wc.monitored_website_id = mw.id
      and wc.checked_at >= now() - interval '7 days'
      and wc.response_ms is not null
  ) as avg_response_ms_7d,
  (
    select count(*)
    from public.website_monitor_changes wmc
    where wmc.monitored_website_id = mw.id
      and wmc.detected_at >= now() - interval '30 days'
  ) as changes_30d
from public.monitored_websites mw
left join public.companies c on c.id = mw.company_id;

grant select on public.monitored_websites_summary to authenticated;
grant select on public.monitored_websites_summary to service_role;

comment on table public.website_monitor_changes is
  'Detected changes to monitored website status, stack, hosting, SSL, etc.';
