alter table if exists public.deals
  add column if not exists contact_id bigint references public.contacts(id) on update cascade on delete set null,
  add column if not exists company_name text,
  add column if not exists project_address text,
  add column if not exists project_place_id text,
  add column if not exists project_address_meta jsonb,
  add column if not exists project_type text,
  add column if not exists estimated_value numeric(12,2),
  add column if not exists notes text,
  add column if not exists salesperson_ids bigint[] not null default '{}',
  add column if not exists subcontractor_ids bigint[] not null default '{}',
  add column if not exists worker_ids bigint[] not null default '{}';

create index if not exists deals_contact_id_idx on public.deals(contact_id);
create index if not exists deals_project_type_idx on public.deals(project_type);
create index if not exists deals_project_stage_idx on public.deals(stage);

create table if not exists public.deal_salespersons (
  id bigint generated by default as identity primary key,
  deal_id bigint not null references public.deals(id) on update cascade on delete cascade,
  person_id bigint not null references public.people(id) on update cascade on delete restrict,
  created_at timestamptz not null default now(),
  unique (deal_id, person_id)
);

create table if not exists public.deal_subcontractors (
  id bigint generated by default as identity primary key,
  deal_id bigint not null references public.deals(id) on update cascade on delete cascade,
  person_id bigint not null references public.people(id) on update cascade on delete restrict,
  created_at timestamptz not null default now(),
  unique (deal_id, person_id)
);

create table if not exists public.deal_workers (
  id bigint generated by default as identity primary key,
  deal_id bigint not null references public.deals(id) on update cascade on delete cascade,
  person_id bigint not null references public.people(id) on update cascade on delete restrict,
  created_at timestamptz not null default now(),
  unique (deal_id, person_id)
);

create table if not exists public.deal_cost_entries (
  id bigint generated by default as identity primary key,
  deal_id bigint not null references public.deals(id) on update cascade on delete cascade,
  cost_type text not null check (cost_type in ('material', 'labor', 'payroll', 'commission', 'other')),
  label text,
  amount numeric(12,2) not null default 0,
  incurred_on date,
  notes text,
  source_reference text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists deal_salespersons_deal_id_idx on public.deal_salespersons(deal_id);
create index if not exists deal_subcontractors_deal_id_idx on public.deal_subcontractors(deal_id);
create index if not exists deal_workers_deal_id_idx on public.deal_workers(deal_id);
create index if not exists deal_cost_entries_deal_id_idx on public.deal_cost_entries(deal_id);

alter table public.deal_salespersons enable row level security;
alter table public.deal_subcontractors enable row level security;
alter table public.deal_workers enable row level security;
alter table public.deal_cost_entries enable row level security;

grant delete, insert, select, update on table public.deal_salespersons to authenticated;
grant delete, insert, select, update on table public.deal_subcontractors to authenticated;
grant delete, insert, select, update on table public.deal_workers to authenticated;
grant delete, insert, select, update on table public.deal_cost_entries to authenticated;

grant delete, insert, references, select, trigger, truncate, update on table public.deal_salespersons to service_role;
grant delete, insert, references, select, trigger, truncate, update on table public.deal_subcontractors to service_role;
grant delete, insert, references, select, trigger, truncate, update on table public.deal_workers to service_role;
grant delete, insert, references, select, trigger, truncate, update on table public.deal_cost_entries to service_role;

create policy "Deal salespersons insert" on public.deal_salespersons as permissive for insert to authenticated with check (true);
create policy "Deal salespersons select" on public.deal_salespersons as permissive for select to authenticated using (true);
create policy "Deal salespersons update" on public.deal_salespersons as permissive for update to authenticated using (true) with check (true);
create policy "Deal salespersons delete" on public.deal_salespersons as permissive for delete to authenticated using (true);

create policy "Deal subcontractors insert" on public.deal_subcontractors as permissive for insert to authenticated with check (true);
create policy "Deal subcontractors select" on public.deal_subcontractors as permissive for select to authenticated using (true);
create policy "Deal subcontractors update" on public.deal_subcontractors as permissive for update to authenticated using (true) with check (true);
create policy "Deal subcontractors delete" on public.deal_subcontractors as permissive for delete to authenticated using (true);

create policy "Deal workers insert" on public.deal_workers as permissive for insert to authenticated with check (true);
create policy "Deal workers select" on public.deal_workers as permissive for select to authenticated using (true);
create policy "Deal workers update" on public.deal_workers as permissive for update to authenticated using (true) with check (true);
create policy "Deal workers delete" on public.deal_workers as permissive for delete to authenticated using (true);

create policy "Deal cost entries insert" on public.deal_cost_entries as permissive for insert to authenticated with check (true);
create policy "Deal cost entries select" on public.deal_cost_entries as permissive for select to authenticated using (true);
create policy "Deal cost entries update" on public.deal_cost_entries as permissive for update to authenticated using (true) with check (true);
create policy "Deal cost entries delete" on public.deal_cost_entries as permissive for delete to authenticated using (true);
