create table if not exists public.employee_pto_adjustments (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references public.people(id) on update cascade on delete cascade,
  adjustment_date date not null default current_date,
  adjustment_type text not null check (adjustment_type in ('sick', 'vacation')),
  days_delta numeric(8,2) not null,
  reason text,
  notes text,
  created_by text,
  created_at timestamp with time zone not null default now()
);

create index if not exists employee_pto_adjustments_employee_idx
  on public.employee_pto_adjustments(employee_id, adjustment_date desc);

alter table public.employee_pto_adjustments enable row level security;

grant delete, insert, select, update on table public.employee_pto_adjustments to authenticated;
grant delete, insert, references, select, trigger, truncate, update on table public.employee_pto_adjustments to service_role;

create policy "Employee PTO adjustments insert" on public.employee_pto_adjustments
  as permissive for insert to authenticated with check (true);
create policy "Employee PTO adjustments select" on public.employee_pto_adjustments
  as permissive for select to authenticated using (true);
create policy "Employee PTO adjustments update" on public.employee_pto_adjustments
  as permissive for update to authenticated using (true) with check (true);
create policy "Employee PTO adjustments delete" on public.employee_pto_adjustments
  as permissive for delete to authenticated using (true);
