-- Web Report: async website audits (Lighthouse + static analysis).
-- Manual trigger only in Phase 1; worker runs outside Supabase Edge.

-- ---------------------------------------------------------------------------
-- Storage bucket for PDF reports (Phase 3; created now per product decision)
-- ---------------------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'website-audits',
  'website-audits',
  false,
  20971520,
  array['application/pdf']::text[]
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "website_audits_storage_read" on storage.objects;
create policy "website_audits_storage_read" on storage.objects
  for select to authenticated
  using (
    bucket_id = 'website-audits'
    and (storage.foldername(name))[1] = public.current_user_org_id()::text
  );

drop policy if exists "website_audits_storage_service" on storage.objects;
create policy "website_audits_storage_service" on storage.objects
  for all to service_role
  using (bucket_id = 'website-audits')
  with check (bucket_id = 'website-audits');

-- ---------------------------------------------------------------------------
-- website_audits
-- ---------------------------------------------------------------------------
create table if not exists public.website_audits (
  id bigint generated by default as identity primary key,
  org_id bigint not null references public.organizations (id) on delete cascade,
  monitored_website_id bigint not null references public.monitored_websites (id) on delete cascade,
  requested_by_member_id bigint references public.organization_members (id) on update cascade on delete set null,
  status text not null default 'queued'
    check (status in ('queued', 'running', 'done', 'failed')),
  audit_url text not null,
  strategy text not null default 'mobile'
    check (strategy in ('mobile', 'desktop')),
  requested_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz,
  overall_score smallint check (overall_score is null or (overall_score >= 0 and overall_score <= 100)),
  score_performance smallint check (score_performance is null or (score_performance >= 0 and score_performance <= 100)),
  score_seo smallint check (score_seo is null or (score_seo >= 0 and score_seo <= 100)),
  score_best_practices smallint check (score_best_practices is null or (score_best_practices >= 0 and score_best_practices <= 100)),
  score_accessibility smallint check (score_accessibility is null or (score_accessibility >= 0 and score_accessibility <= 100)),
  lab_lcp_ms numeric,
  lab_cls numeric,
  lab_tbt_ms numeric,
  field_lcp_ms numeric,
  field_cls numeric,
  field_inp_ms numeric,
  crux_has_data boolean not null default false,
  static_json jsonb not null default '{}'::jsonb,
  lighthouse_json jsonb,
  axe_json jsonb,
  crux_json jsonb,
  pdf_storage_path text,
  error_message text,
  worker_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.website_audits is
  'Async web audit reports (Lighthouse + static). One row per run; history preserved.';

create index if not exists website_audits_site_requested_idx
  on public.website_audits (monitored_website_id, requested_at desc);

create index if not exists website_audits_org_status_idx
  on public.website_audits (org_id, status);

create index if not exists website_audits_active_status_idx
  on public.website_audits (status, requested_at)
  where status in ('queued', 'running');

-- At most one queued/running audit per monitored site (DB + enqueue guard).
create unique index if not exists website_audits_one_active_per_site
  on public.website_audits (monitored_website_id)
  where status in ('queued', 'running');

-- ---------------------------------------------------------------------------
-- audit_findings
-- ---------------------------------------------------------------------------
create table if not exists public.audit_findings (
  id bigint generated by default as identity primary key,
  org_id bigint not null references public.organizations (id) on delete cascade,
  audit_id bigint not null references public.website_audits (id) on delete cascade,
  category text not null
    check (category in ('performance', 'seo', 'a11y', 'security', 'static', 'best_practices')),
  severity text not null
    check (severity in ('critico', 'importante', 'nice-to-have')),
  source text not null
    check (source in ('lighthouse', 'axe', 'static', 'crux', 'nomi')),
  source_id text,
  title text not null,
  description text,
  recommendation text,
  commercial_message text,
  metric_key text,
  metric_value text,
  display_order smallint not null default 0,
  created_at timestamptz not null default now()
);

comment on table public.audit_findings is
  'Normalized audit findings with Nomi commercial severity prioritization.';

create index if not exists audit_findings_audit_order_idx
  on public.audit_findings (audit_id, severity, display_order);

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------
alter table public.website_audits enable row level security;
alter table public.audit_findings enable row level security;

grant select, insert on table public.website_audits to authenticated;
grant select on table public.audit_findings to authenticated;
grant all on table public.website_audits to service_role;
grant all on table public.audit_findings to service_role;

grant usage, select on sequence public.website_audits_id_seq to authenticated, service_role;
grant usage, select on sequence public.audit_findings_id_seq to service_role;

drop policy if exists "website_audits_org_scoped" on public.website_audits;
create policy "website_audits_org_scoped" on public.website_audits
  for select to authenticated
  using (org_id = public.current_user_org_id());

drop policy if exists "website_audits_insert_org" on public.website_audits;
create policy "website_audits_insert_org" on public.website_audits
  for insert to authenticated
  with check (org_id = public.current_user_org_id());

drop policy if exists "audit_findings_org_scoped" on public.audit_findings;
create policy "audit_findings_org_scoped" on public.audit_findings
  for select to authenticated
  using (org_id = public.current_user_org_id());

drop trigger if exists trg_website_audits_assign_org on public.website_audits;
create trigger trg_website_audits_assign_org
  before insert on public.website_audits
  for each row execute function public.trg_assign_org_id_from_session();

drop trigger if exists trg_audit_findings_assign_org on public.audit_findings;
create trigger trg_audit_findings_assign_org
  before insert on public.audit_findings
  for each row execute function public.trg_assign_org_id_from_session();

-- ---------------------------------------------------------------------------
-- updated_at trigger helper (reuse if already present)
-- ---------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_website_audits_updated_at on public.website_audits;
create trigger trg_website_audits_updated_at
  before update on public.website_audits
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Realtime (live audit status in UI)
-- ---------------------------------------------------------------------------
alter table public.website_audits replica identity full;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'website_audits'
  ) then
    alter publication supabase_realtime add table public.website_audits;
  end if;
end $$;

-- ---------------------------------------------------------------------------
-- Summary view: latest audit per site
-- ---------------------------------------------------------------------------
create or replace view public.website_audits_latest
with (security_invoker = true)
as
select distinct on (wa.monitored_website_id)
  wa.*
from public.website_audits wa
order by wa.monitored_website_id, wa.requested_at desc;

grant select on public.website_audits_latest to authenticated;
grant select on public.website_audits_latest to service_role;
