-- CRM Claude Assistant: conversation history (org + member scoped).

create table if not exists public.assistant_conversations (
  id bigint generated by default as identity primary key,
  org_id bigint not null references public.organizations (id) on delete cascade,
  member_id bigint not null references public.organization_members (id) on delete cascade,
  title text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists assistant_conversations_member_updated_idx
  on public.assistant_conversations (member_id, updated_at desc);

create table if not exists public.assistant_messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.assistant_conversations (id) on delete cascade,
  org_id bigint not null references public.organizations (id) on delete cascade,
  member_id bigint not null references public.organization_members (id) on delete cascade,
  role text not null check (role in ('user', 'assistant', 'tool', 'system')),
  content text not null default '',
  tool_name text,
  tool_payload jsonb,
  created_at timestamptz not null default now()
);

create index if not exists assistant_messages_conversation_created_idx
  on public.assistant_messages (conversation_id, created_at asc);

alter table public.assistant_conversations enable row level security;
alter table public.assistant_messages enable row level security;

create policy "assistant_conversations_select_own"
  on public.assistant_conversations
  for select to authenticated
  using (
    org_id = public.current_user_org_id()
    and member_id = (
      select m.id from public.organization_members m where m.user_id = auth.uid() limit 1
    )
  );

create policy "assistant_conversations_insert_own"
  on public.assistant_conversations
  for insert to authenticated
  with check (
    org_id = public.current_user_org_id()
    and member_id = (
      select m.id from public.organization_members m where m.user_id = auth.uid() limit 1
    )
  );

create policy "assistant_conversations_update_own"
  on public.assistant_conversations
  for update to authenticated
  using (
    org_id = public.current_user_org_id()
    and member_id = (
      select m.id from public.organization_members m where m.user_id = auth.uid() limit 1
    )
  )
  with check (
    org_id = public.current_user_org_id()
    and member_id = (
      select m.id from public.organization_members m where m.user_id = auth.uid() limit 1
    )
  );

create policy "assistant_conversations_delete_own"
  on public.assistant_conversations
  for delete to authenticated
  using (
    org_id = public.current_user_org_id()
    and member_id = (
      select m.id from public.organization_members m where m.user_id = auth.uid() limit 1
    )
  );

create policy "assistant_messages_select_own"
  on public.assistant_messages
  for select to authenticated
  using (
    org_id = public.current_user_org_id()
    and member_id = (
      select m.id from public.organization_members m where m.user_id = auth.uid() limit 1
    )
  );

create policy "assistant_messages_insert_own"
  on public.assistant_messages
  for insert to authenticated
  with check (
    org_id = public.current_user_org_id()
    and member_id = (
      select m.id from public.organization_members m where m.user_id = auth.uid() limit 1
    )
  );

grant select, insert, update, delete on public.assistant_conversations to authenticated;
grant select, insert on public.assistant_messages to authenticated;
grant usage, select on sequence public.assistant_conversations_id_seq to authenticated;
grant usage, select on sequence public.assistant_messages_id_seq to authenticated;
