-- Short-lived anti-CSRF state tokens for the Zoho OAuth redirect
-- handshake. Each row is consumed exactly once by /oauth-callback.

create table if not exists public.zoho_oauth_states (
  id             bigint generated by default as identity primary key,
  org_id         bigint not null references public.organizations(id) on delete cascade,
  state          text   not null,
  region         text   not null default 'com',
  redirect_after text   null,
  initiated_by   uuid   null references auth.users(id) on delete set null,
  created_at     timestamp with time zone not null default now(),
  expires_at     timestamp with time zone not null default (now() + interval '15 minutes'),
  used_at        timestamp with time zone null
);

create unique index if not exists zoho_oauth_states_state_uidx
  on public.zoho_oauth_states(state);
create index if not exists zoho_oauth_states_org_idx
  on public.zoho_oauth_states(org_id, created_at desc);

alter table public.zoho_oauth_states enable row level security;

drop policy if exists zoho_oauth_states_service_role_all on public.zoho_oauth_states;
create policy zoho_oauth_states_service_role_all
  on public.zoho_oauth_states
  as permissive
  for all
  to service_role
  using (true)
  with check (true);

comment on table public.zoho_oauth_states is 'Short-lived anti-CSRF state tokens for the Zoho OAuth redirect handshake. Each row is consumed exactly once by /oauth-callback.';
