-- Google Search Console (agency OAuth + search analytics snapshots).

create table if not exists public.google_gsc_oauth_states (
  id bigint generated by default as identity primary key,
  org_id bigint not null references public.organizations (id) on delete cascade,
  state text not null,
  redirect_after text,
  initiated_by uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '15 minutes'),
  used_at timestamptz
);

create unique index if not exists google_gsc_oauth_states_state_uidx
  on public.google_gsc_oauth_states (state);

create index if not exists google_gsc_oauth_states_org_idx
  on public.google_gsc_oauth_states (org_id, created_at desc);

alter table public.google_gsc_oauth_states enable row level security;

drop policy if exists google_gsc_oauth_states_service_role_all
  on public.google_gsc_oauth_states;
create policy google_gsc_oauth_states_service_role_all
  on public.google_gsc_oauth_states
  for all to service_role
  using (true)
  with check (true);

create table if not exists public.google_gsc_credentials (
  org_id bigint primary key references public.organizations (id) on delete cascade,
  google_email text,
  refresh_token text not null,
  access_token text,
  access_token_expires_at timestamptz,
  scopes text[] not null default '{}',
  connected_by uuid references auth.users (id) on delete set null,
  last_synced_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.google_gsc_credentials is
  'Agency-level Google Search Console OAuth (one Google account per org).';

alter table public.google_gsc_credentials enable row level security;

drop policy if exists google_gsc_credentials_service_role_all
  on public.google_gsc_credentials;
create policy google_gsc_credentials_service_role_all
  on public.google_gsc_credentials
  for all to service_role
  using (true)
  with check (true);

alter table public.monitored_websites
  add column if not exists gsc_site_url text;

comment on column public.monitored_websites.gsc_site_url is
  'Search Console property URL (e.g. sc-domain:example.com or https://example.com/).';

create table if not exists public.gsc_search_analytics_snapshots (
  id bigint generated by default as identity primary key,
  org_id bigint not null references public.organizations (id) on delete cascade,
  monitored_website_id bigint not null references public.monitored_websites (id) on delete cascade,
  site_url text not null,
  period_start date not null,
  period_end date not null,
  totals jsonb not null default '{}'::jsonb,
  top_queries jsonb not null default '[]'::jsonb,
  top_pages jsonb not null default '[]'::jsonb,
  fetched_at timestamptz not null default now()
);

create index if not exists gsc_snapshots_site_fetched_idx
  on public.gsc_search_analytics_snapshots (monitored_website_id, fetched_at desc);

create index if not exists gsc_snapshots_org_fetched_idx
  on public.gsc_search_analytics_snapshots (org_id, fetched_at desc);

comment on table public.gsc_search_analytics_snapshots is
  'Cached Search Console searchAnalytics (typically last 28 days).';

alter table public.gsc_search_analytics_snapshots enable row level security;

grant select on table public.gsc_search_analytics_snapshots to authenticated;
grant all on table public.gsc_search_analytics_snapshots to service_role;

drop policy if exists gsc_snapshots_org_scoped on public.gsc_search_analytics_snapshots;
create policy gsc_snapshots_org_scoped on public.gsc_search_analytics_snapshots
  for select to authenticated
  using (org_id = public.current_user_org_id());

drop policy if exists gsc_snapshots_service_role_all on public.gsc_search_analytics_snapshots;
create policy gsc_snapshots_service_role_all on public.gsc_search_analytics_snapshots
  for all to service_role
  using (true)
  with check (true);

create or replace function public.tg_google_gsc_credentials_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_google_gsc_credentials_updated_at on public.google_gsc_credentials;
create trigger trg_google_gsc_credentials_updated_at
  before update on public.google_gsc_credentials
  for each row execute function public.tg_google_gsc_credentials_set_updated_at();
