-- Zoho CRM "Leads" module is separate from "Contacts" in Zoho. We import
-- Zoho Leads as Nomi contacts with status='lead' (so they live in the
-- Anti-Olvido flow) and keep their Zoho id under a distinct column so
-- they never collide with Zoho Contacts (which use contacts.zoho_id).

alter table public.contacts add column if not exists lead_zoho_id text;
create unique index if not exists contacts_org_lead_zoho_id_uidx
  on public.contacts(org_id, lead_zoho_id) where lead_zoho_id is not null;
comment on column public.contacts.lead_zoho_id is 'Zoho CRM Leads-module id (distinct from Contacts-module id) for one-shot import idempotency.';

create table if not exists public.zoho_leads_raw (
  id                   bigint generated by default as identity primary key,
  org_id               bigint not null references public.organizations(id) on delete cascade,
  zoho_id              text   not null,
  payload              jsonb  not null,
  imported_at          timestamp with time zone not null default now(),
  promoted_at          timestamp with time zone null,
  promoted_contact_id  bigint null references public.contacts(id) on delete set null,
  promotion_error      text   null,
  unique (org_id, zoho_id)
);

create index if not exists zoho_leads_raw_org_idx
  on public.zoho_leads_raw(org_id, imported_at desc);
create index if not exists zoho_leads_raw_unpromoted_idx
  on public.zoho_leads_raw(org_id) where promoted_at is null;

alter table public.zoho_leads_raw enable row level security;

drop policy if exists zoho_leads_raw_service_role_all on public.zoho_leads_raw;
create policy zoho_leads_raw_service_role_all
  on public.zoho_leads_raw
  as permissive
  for all
  to service_role
  using (true)
  with check (true);

comment on table public.zoho_leads_raw is 'Raw Zoho CRM Lead records pulled by zoho_oneshot_import /sync-all. Promoted to public.contacts (status=lead, lead_stage mapped) by /promote.';
