alter table if exists public.deals
  add column if not exists original_project_value numeric(12,2),
  add column if not exists current_project_value numeric(12,2),
  add column if not exists value_includes_material boolean not null default false,
  add column if not exists start_date date,
  add column if not exists expected_end_date date,
  add column if not exists actual_completion_date date,
  add column if not exists estimated_completion_time text;

create table if not exists public.deal_subcontractor_entries (
  id bigint generated by default as identity primary key,
  deal_id bigint not null references public.deals(id) on update cascade on delete cascade,
  person_id bigint not null references public.people(id) on update cascade on delete restrict,
  status text not null default 'pending' check (status in ('pending', 'approved', 'in_progress', 'completed', 'paid')),
  invoice_number text,
  invoice_attachments jsonb not null default '[]'::jsonb,
  cost_amount numeric(12,2) not null default 0,
  material_included boolean not null default false,
  estimated_completion_date date,
  start_date date,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.deal_expenses (
  id bigint generated by default as identity primary key,
  deal_id bigint not null references public.deals(id) on update cascade on delete cascade,
  expense_type text not null default 'other',
  vendor text,
  description text,
  amount numeric(12,2) not null default 0,
  purchase_date date,
  paid boolean not null default false,
  attachments jsonb not null default '[]'::jsonb,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.deal_change_orders (
  id bigint generated by default as identity primary key,
  deal_id bigint not null references public.deals(id) on update cascade on delete cascade,
  title text not null,
  description text,
  change_date date not null default current_date,
  amount numeric(12,2) not null default 0,
  reason text,
  status text not null default 'draft' check (status in ('draft', 'sent', 'approved', 'rejected')),
  attachments jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.deal_commissions (
  id bigint generated by default as identity primary key,
  deal_id bigint not null references public.deals(id) on update cascade on delete cascade,
  salesperson_id bigint not null references public.people(id) on update cascade on delete restrict,
  commission_type text not null check (commission_type in ('fixed', 'percentage')),
  commission_value numeric(12,4) not null default 0,
  basis text not null default 'payments_collected' check (basis in ('payments_collected', 'custom')),
  paid boolean not null default false,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.deal_client_payments (
  id bigint generated by default as identity primary key,
  deal_id bigint not null references public.deals(id) on update cascade on delete cascade,
  payment_date date not null default current_date,
  amount numeric(12,2) not null default 0,
  payment_method text not null default 'other' check (payment_method in ('check', 'cash', 'zelle', 'ach', 'card', 'other')),
  check_number text,
  reference_number text,
  status text not null default 'pending' check (status in ('pending', 'cleared', 'bounced', 'deposited')),
  attachments jsonb not null default '[]'::jsonb,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists deal_subcontractor_entries_deal_id_idx on public.deal_subcontractor_entries(deal_id);
create index if not exists deal_expenses_deal_id_idx on public.deal_expenses(deal_id);
create index if not exists deal_change_orders_deal_id_idx on public.deal_change_orders(deal_id);
create index if not exists deal_commissions_deal_id_idx on public.deal_commissions(deal_id);
create index if not exists deal_client_payments_deal_id_idx on public.deal_client_payments(deal_id);

alter table public.deal_subcontractor_entries enable row level security;
alter table public.deal_expenses enable row level security;
alter table public.deal_change_orders enable row level security;
alter table public.deal_commissions enable row level security;
alter table public.deal_client_payments enable row level security;

grant delete, insert, select, update on table public.deal_subcontractor_entries to authenticated;
grant delete, insert, select, update on table public.deal_expenses to authenticated;
grant delete, insert, select, update on table public.deal_change_orders to authenticated;
grant delete, insert, select, update on table public.deal_commissions to authenticated;
grant delete, insert, select, update on table public.deal_client_payments to authenticated;

grant delete, insert, references, select, trigger, truncate, update on table public.deal_subcontractor_entries to service_role;
grant delete, insert, references, select, trigger, truncate, update on table public.deal_expenses to service_role;
grant delete, insert, references, select, trigger, truncate, update on table public.deal_change_orders to service_role;
grant delete, insert, references, select, trigger, truncate, update on table public.deal_commissions to service_role;
grant delete, insert, references, select, trigger, truncate, update on table public.deal_client_payments to service_role;

create policy "Deal subcontractor entries insert" on public.deal_subcontractor_entries as permissive for insert to authenticated with check (true);
create policy "Deal subcontractor entries select" on public.deal_subcontractor_entries as permissive for select to authenticated using (true);
create policy "Deal subcontractor entries update" on public.deal_subcontractor_entries as permissive for update to authenticated using (true) with check (true);
create policy "Deal subcontractor entries delete" on public.deal_subcontractor_entries as permissive for delete to authenticated using (true);

create policy "Deal expenses insert" on public.deal_expenses as permissive for insert to authenticated with check (true);
create policy "Deal expenses select" on public.deal_expenses as permissive for select to authenticated using (true);
create policy "Deal expenses update" on public.deal_expenses as permissive for update to authenticated using (true) with check (true);
create policy "Deal expenses delete" on public.deal_expenses as permissive for delete to authenticated using (true);

create policy "Deal change orders insert" on public.deal_change_orders as permissive for insert to authenticated with check (true);
create policy "Deal change orders select" on public.deal_change_orders as permissive for select to authenticated using (true);
create policy "Deal change orders update" on public.deal_change_orders as permissive for update to authenticated using (true) with check (true);
create policy "Deal change orders delete" on public.deal_change_orders as permissive for delete to authenticated using (true);

create policy "Deal commissions insert" on public.deal_commissions as permissive for insert to authenticated with check (true);
create policy "Deal commissions select" on public.deal_commissions as permissive for select to authenticated using (true);
create policy "Deal commissions update" on public.deal_commissions as permissive for update to authenticated using (true) with check (true);
create policy "Deal commissions delete" on public.deal_commissions as permissive for delete to authenticated using (true);

create policy "Deal client payments insert" on public.deal_client_payments as permissive for insert to authenticated with check (true);
create policy "Deal client payments select" on public.deal_client_payments as permissive for select to authenticated using (true);
create policy "Deal client payments update" on public.deal_client_payments as permissive for update to authenticated using (true) with check (true);
create policy "Deal client payments delete" on public.deal_client_payments as permissive for delete to authenticated using (true);
