-- Internal team chat (Twilio-ready: channel + direction on messages, client conversations later).

create or replace function public.current_user_member_id()
returns bigint
language sql
stable
security definer
set search_path = public
as $$
  select m.id
  from public.organization_members m
  where m.user_id = auth.uid()
  limit 1;
$$;

grant execute on function public.current_user_member_id() to authenticated;

create table if not exists public.conversations (
  id bigint generated by default as identity primary key,
  org_id bigint not null references public.organizations (id) on delete cascade,
  type text not null check (type in ('team_dm', 'project', 'client')),
  title text,
  deal_id bigint references public.deals (id) on update cascade on delete cascade,
  contact_id bigint references public.contacts (id) on update cascade on delete set null,
  external_phone text,
  dm_key text,
  last_message_at timestamptz,
  created_by_member_id bigint references public.organization_members (id) on update cascade on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.conversation_participants (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.conversations (id) on delete cascade,
  member_id bigint not null references public.organization_members (id) on update cascade on delete cascade,
  last_read_at timestamptz,
  created_at timestamptz not null default now(),
  unique (conversation_id, member_id)
);

create table if not exists public.conversation_messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.conversations (id) on delete cascade,
  author_member_id bigint references public.organization_members (id) on update cascade on delete set null,
  body text not null,
  channel text not null default 'internal' check (channel in ('internal', 'sms', 'whatsapp')),
  direction text not null default 'outbound' check (direction in ('outbound', 'inbound')),
  external_id text,
  created_at timestamptz not null default now()
);

create index if not exists conversations_org_id_idx
  on public.conversations (org_id);

create index if not exists conversations_deal_id_idx
  on public.conversations (deal_id)
  where deal_id is not null;

create unique index if not exists conversations_project_deal_uidx
  on public.conversations (deal_id)
  where type = 'project' and deal_id is not null;

create unique index if not exists conversations_dm_key_uidx
  on public.conversations (org_id, dm_key)
  where type = 'team_dm' and dm_key is not null;

create index if not exists conversations_last_message_at_idx
  on public.conversations (last_message_at desc nulls last);

create index if not exists conversation_participants_member_id_idx
  on public.conversation_participants (member_id);

create index if not exists conversation_messages_conversation_id_idx
  on public.conversation_messages (conversation_id, created_at);

alter table public.conversations enable row level security;
alter table public.conversation_participants enable row level security;
alter table public.conversation_messages enable row level security;

grant select, insert, update, delete on public.conversations to authenticated;
grant select, insert, update, delete on public.conversation_participants to authenticated;
grant select, insert, update, delete on public.conversation_messages to authenticated;

grant all on public.conversations to service_role;
grant all on public.conversation_participants to service_role;
grant all on public.conversation_messages to service_role;

create or replace function public.is_conversation_participant(
  conv_id bigint,
  member_id bigint
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.conversation_participants cp
    where cp.conversation_id = conv_id
      and cp.member_id = member_id
  );
$$;

grant execute on function public.is_conversation_participant(bigint, bigint) to authenticated;

create or replace function public.user_can_access_conversation(conv_id bigint)
returns boolean
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  allowed boolean;
begin
  perform set_config('row_security', 'off', true);

  select exists (
    select 1
    from public.conversations c
    where c.id = conv_id
      and c.org_id = public.current_user_org_id()
      and (
        c.type = 'project'
        or c.created_by_member_id = public.current_user_member_id()
        or public.is_conversation_participant(c.id, public.current_user_member_id())
      )
  )
  into allowed;

  return coalesce(allowed, false);
end;
$$;

grant execute on function public.user_can_access_conversation(bigint) to authenticated;

drop policy if exists "conversations_access" on public.conversations;
create policy "conversations_access" on public.conversations
  for all to authenticated
  using (
    org_id = public.current_user_org_id()
    and (
      type = 'project'
      or created_by_member_id = public.current_user_member_id()
      or public.is_conversation_participant(id, public.current_user_member_id())
    )
  )
  with check (
    org_id = public.current_user_org_id()
    and (
      type = 'project'
      or created_by_member_id = public.current_user_member_id()
      or public.is_conversation_participant(id, public.current_user_member_id())
    )
  );

drop policy if exists "conversation_participants_access" on public.conversation_participants;
create policy "conversation_participants_access" on public.conversation_participants
  for all to authenticated
  using (
    member_id = public.current_user_member_id()
    or exists (
      select 1
      from public.conversations c
      where c.id = conversation_participants.conversation_id
        and c.org_id = public.current_user_org_id()
        and (
          c.type = 'project'
          or c.created_by_member_id = public.current_user_member_id()
        )
    )
  )
  with check (
    member_id = public.current_user_member_id()
    or exists (
      select 1
      from public.conversations c
      where c.id = conversation_participants.conversation_id
        and c.org_id = public.current_user_org_id()
        and c.created_by_member_id = public.current_user_member_id()
    )
  );

drop policy if exists "conversation_messages_access" on public.conversation_messages;
create policy "conversation_messages_access" on public.conversation_messages
  for all to authenticated
  using (public.user_can_access_conversation(conversation_id))
  with check (
    public.user_can_access_conversation(conversation_id)
    and (
      author_member_id is null
      or author_member_id = public.current_user_member_id()
    )
  );

create or replace function public.trg_conversation_message_touch_conversation()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.conversations
  set
    last_message_at = new.created_at,
    updated_at = now()
  where id = new.conversation_id;
  return new;
end;
$$;

drop trigger if exists trg_conversation_message_touch_conversation on public.conversation_messages;
create trigger trg_conversation_message_touch_conversation
  after insert on public.conversation_messages
  for each row execute function public.trg_conversation_message_touch_conversation();

drop trigger if exists trg_assign_org_id_conversations on public.conversations;
create trigger trg_assign_org_id_conversations
  before insert on public.conversations
  for each row execute function public.trg_assign_org_id_from_session();

do $$
begin
  alter publication supabase_realtime add table public.conversation_messages;
exception
  when duplicate_object then null;
end $$;
